[Readme] 对于自述文件的简单美化
Hex-Dragon/PCL2 pull request #193
Opened 2022-10-06 14:08 UTC by liubanlaobanzhang

好吧……我还是看不下去了……

帮着龙猫做了一下Readme的优化（ #191 ）。。。

部分是从爱发电上面盘下来的……

而且非常正经.png

2022-10-06 17:09 UTC, Big-Cake-jpg requested changes

2022-10-06 17:09 UTC, Big-Cake-jpg commented on README.md
> +  使用`PCL 2`时遇到了问题？亦或者有新的想法，希望作者开发出新的功能？你可以在[`Issues`](https://github.com/Hex-Dragon/PCL2/issues/new/choose)提出！
PCL 和 2 之间不要用空格隔开

2022-10-06 23:34 UTC, liubanlaobanzhang commented on README.md
> +  使用`PCL 2`时遇到了问题？亦或者有新的想法，希望作者开发出新的功能？你可以在[`Issues`](https://github.com/Hex-Dragon/PCL2/issues/new/choose)提出！
好

2022-10-07 02:12 UTC, liubanlaobanzhang commented on README.md
> +  使用`PCL 2`时遇到了问题？亦或者有新的想法，希望作者开发出新的功能？你可以在[`Issues`](https://github.com/Hex-Dragon/PCL2/issues/new/choose)提出！
已经完成了修改（在 提交4950059）

2022-10-07 04:25 UTC, Big-Cake-jpg requested changes

2022-10-07 04:25 UTC, Big-Cake-jpg commented on README.md
> +- 这个 PCL2 被部分内测成员戏称为“PCLDownloader”，因为其内置的多线程下载实在太厉害了……甚至有时都强过了IDM……
这一行可能有必要删去......？

如果不需要删的话，中文和英文之间需要使用空格隔开。

2022-10-07 04:27 UTC, liubanlaobanzhang commented on README.md
> +- 这个 PCL2 被部分内测成员戏称为“PCLDownloader”，因为其内置的多线程下载实在太厉害了……甚至有时都强过了IDM……
这个是龙猫留下来的……

2022-10-07 04:27 UTC, liubanlaobanzhang commented on README.md
> +- 这个 PCL2 被部分内测成员戏称为“PCLDownloader”，因为其内置的多线程下载实在太厉害了……甚至有时都强过了IDM……
算了 改一下吧

2022-10-07 04:31 UTC, Big-Cake-jpg commented on README.md
> +- 这个 PCL2 被部分内测成员戏称为“PCLDownloader”，因为其内置的多线程下载实在太厉害了……甚至有时都强过了IDM……
> 算了 改一下吧

呃，我说的是 IDM 那一行。

如果是龙猫留下来的，当我没说

2022-10-07 04:34 UTC, liubanlaobanzhang commented on README.md
> +- 这个 PCL2 被部分内测成员戏称为“PCLDownloader”，因为其内置的多线程下载实在太厉害了……甚至有时都强过了IDM……
Emm 

好吧 这一行确实是我加的……但是好像网页编辑器里有bug（我现在在用平板写代码）

我怎么改都加不进空格……

只能加一个`外嵌套`了

2022-10-07 08:51 UTC, Big-Cake-jpg requested changes

2022-10-07 08:51 UTC, Big-Cake-jpg commented on README.md
> +`经历了 DMCA Takedown 等重重波折，这个存储库终于开放了。`
经历了 DMCA Takedown 等重重波折，这个存储库终于重新开放了。

2022-10-07 08:51 UTC, Big-Cake-jpg commented on README.md
> +  请见 [@LTCatt: 关于PCL2 功能投票·Discussion #2](https://github.com/Hex-Dragon/PCL2/discussions/2)。
关于 PCL2 功能投票·Discussion #2

2022-10-07 08:51 UTC, Big-Cake-jpg commented on README.md
> +  - [PCL1](https://github.com/LTCatt/PCL1) 这是个古老的项目
```
[PCL1](https://github.com/LTCatt/PCL1) PCL2 的前身，PCL1
```

2022-10-07 09:25 UTC, liubanlaobanzhang commented
Uhh 等一等等一等 

让我把我自己的作文改完第7稿……

😅

2022-10-07 10:09 UTC, Big-Cake-jpg approved these changes

2022-10-07 18:13 UTC, LTCatt requested changes

2022-10-07 18:13 UTC, LTCatt commented on README.md
> +所以，虽然你不能直接复制粘贴代码到自己的项目，但可以参考其中的逻辑，然后自己车一套更好的……总之，可以借鉴，不要复制啦。
这一段没必要，感兴趣的话 licence 就有了 =。=

2022-10-07 18:13 UTC, LTCatt commented on README.md
> +- 还有，不要想着在 Releases 里面找到内测版的下载链接了，你大概率是找不到的.psd
没必要，删了吧.jpg

2022-10-07 18:13 UTC, LTCatt commented on README.md
> +---
同样没必要，不要放黑历史喂

2022-10-07 18:13 UTC, LTCatt commented on README.md
> +  请见 `关于 PCL2 功能投票·Discussion` [#2](https://github.com/Hex-Dragon/PCL2/discussion/2)
在后面补充加成超链接就行

2022-10-07 18:13 UTC, LTCatt commented on README.md
> +
其实不建议在这里放任何图片，根目录下为了 readme 还得额外多东西属实没啥必要，图片还是删了吧……

2022-10-08 13:29 UTC, liubanlaobanzhang commented
### 然后是 PCL2 图标问题……

当时试图从爱发电的开发者通讯里面直接引用过来 不过不知道是不是 Github 的网页编辑器问题，它插不进来……所以就想到了在仓库里面留原文件qwq

### 一堆的 Commit 问题：
用的是网页编辑器，而且想到什么就加什么（加上周末社区里已经有人提出了好几条建议，因此每一个 Commit 都会对应着一个 审查意见）

### 再解释一下为什么要把一个平平无奇的 Readme 改掉：

_首先说明，每个人有不同的审美观，有的人可能认为 Readme 应该言简意赅，但以我的审美观做布局安排，则会把大多数的内容安插在 Readme 而不是 Wiki，并且会在前面加目录……不过这次忘了加了 (run_

主要原因是看了很多大佬的 Readme（ 比如 Richasy/Bili.UWP ），总觉得这个过于平淡的 Readme 配不大上这么精妙的代码（虽然说感觉代码里面的变量什么确实挺乱，不过在国内确实是一款口碑极佳的启动器），而且有的小白是从 Readme 是否精美来判断项目好坏的……

不然的话我可能只会在 Pull Request 加一个当时在`爱发电`里的制作组通讯的链接，拿来当一个说明文件，也就不会再合并很多了……

### 另外提一嘴：目前还没搞明白怎么从网页编辑器里导进 Github ，估计加了就会好一点了吧……
>  我看了眼，感觉还是比较单调的。
>  但至少或不是太差。

---

这几天忙着月考和期中考（九年级的学业还是比较紧张的，一元二次方程快把我搞晕了 (ToT) ），就等周末再过来填这个 Pull Request 的坑吧……当然也感谢龙猫和其他社区小伙伴们提供的宝贵建议，也是我最近做其他开源的极佳建议……awa

2022-10-08 14:04 UTC, liubanlaobanzhang commented
真不好意思啊……几分钟前发完一篇比较严肃的声明就来看PR意见，语气可能有点硬……所以刚刚说的话如有冒犯，还请包涵一下哈。🙏

主要是我翻过的项目在 Readme 里面都会对这些内容作出很明显的标注 `（因此导致我的习惯也是这样）`，然后又看到了这个比较简单的 Readme，就在Discussion #191 提了这个，后来闲下来就索性自己PR了。。。 U ´ᴥ` U

大家对于 Readme 的理解可能不尽相同，但还能为这个依然很简陋（实际上写完之后我自己也这么觉得，跟我自己的那个项目比起来确实挺差的）的PR提出这么多有利的建议，也非常感激了。🤝

图片的问题我再试着改一下吧 换个图床试试 再实在不行就用刚刚提到的 HTML img嵌入罢……（悲）

~~一元二次方程确实是在九年级学的（我们用的是北师大版）包括公式法 配方法 因式分解法什么的~~

2022-10-08 14:22 UTC, Big-Cake-jpg commented
> ~~一元二次方程确实是在九年级学的（我们用的是北师大版）包括公式法 配方法 因式分解法什么的~~

北师大版？这个好像初二就有了吧（run

2022-10-08 14:23 UTC, liubanlaobanzhang commented
（点错了
~~我们确实是在九年级学……八年级学的是二元一次方程啊~~

2022-10-09 07:09 UTC, z0z0r4 commented
初一就该学点了吧…等到初二才学我这会被笑（

2022-10-09 07:19 UTC, z0z0r4 commented
还好没真像你仓库里面那个readme一样改成detail…

2022-10-09 07:19 UTC, z0z0r4 commented
> 还好没真像你仓库里面那个readme一样改成detail…

直接蚌不住

2022-10-09 12:36 UTC, liubanlaobanzhang commented
> > 还好没真像你仓库里面那个readme一样改成detail…
> 
> 直接蚌不住

😅那个就算是彻底废了

2022-10-09 12:37 UTC, liubanlaobanzhang commented on README.md
umm 
我在考虑之前恶意 DMCA Takedown 的消息是不是要挪到最后面的无趣细节里面
这个事件挪到`简介`里面属实不大好

然后整个最开头我需要周末抽时间重新设计 预期效果跟这个差不多

2022-10-09 12:40 UTC, liubanlaobanzhang commented
> > > 还好没真像你仓库里面那个readme一样改成detail…
> > 
> > 直接蚌不住
> 
> 😅那个就算是彻底废了

那个仓库的后面会再改
毕竟开源项目不能被一个过于花里胡哨的 README 给废了

2022-10-09 13:07 UTC, liubanlaobanzhang commented
emm 
在 .NET 这个语言里我比较外行

这个项目如果要在本地编辑 除了需要 .NET 的开发环境以外
还需要什么特殊的要求吗 
比如 `特殊的控件` 或者 `特殊的 IDLE/开发环境` 什么的

~~主要龙猫没写开发环境和方式，我这个外行很心虚啊~~

2022-10-09 15:22 UTC, LTCatt commented
> emm 在 .NET 这个语言里我比较外行
> 
> 这个项目如果要在本地编辑 除了需要 .NET 的开发环境以外 还需要什么特殊的要求吗 比如 `特殊的控件` 或者 `特殊的 IDLE/开发环境` 什么的
> 
> ~主要龙猫没写开发环境和方式，我这个外行很心虚啊~

没有……（我觉得这个也没啥必要在 readme 写很详细……

2022-10-10 14:01 UTC, liubanlaobanzhang commented
> 
> > 只是过段日子我可能会重新开一个PR 
> ~我也嫌弃 `Commit` 太乱了（run~
> 
> Git reset后强制push就可以了 或 请开发者在后续做些许调整
> ~我前天写完了开源许可 但后来反复改了好多次之后就摆了~
> 于是 这种事你摆到~世界末日~开花者一胎八个也没有关系的！(

😅😅哈哈哈哈哈 龙猫看了不得打你（

强制push……倒确实也可以（你不说我就忘了

2022-10-10 14:24 UTC, liubanlaobanzhang commented
> emoji是滥用吗？我本人对其极度反感，并且有明显感觉你在故意恶俗我。
> 
> Original:
> From:老班长< ***@***.***>Date:2022-10-10 22:01:54To:Hex-Dragon/PCL2< ***@***.***>Cc:nya< ***@***.***>、Comment< ***@***.***>Subject:Re: [Hex-Dragon/PCL2] [Readme] 对于自述文件的简单美化 (PR #193)
> 只是过段日子我可能会重新开一个PR
>  我也嫌弃 Commit 太乱了（run
> Git reset后强制push就可以了 或 请开发者在后续做些许调整
>  我前天写完了开源许可 但后来反复改了好多次之后就摆了
>  于是 这种事你摆到世界末日开花者一胎八个也没有关系的！(
> 😅😅哈哈哈哈哈 龙猫看了不得打你（
> 强制push……倒确实也可以（你不说我就忘了
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>
> 
> 
> 
> 

？没看懂啊
或许是我的理解问题？（我那个emoji指的是“开花者一胎八个” 然后我没有找到“捂脸” 就临时找了个这个代替）

2022-10-10 14:25 UTC, liubanlaobanzhang commented
？发生什么事了呀
让你不舒服了吗？如果是这样的话我道歉

2022-10-10 14:34 UTC, liubanlaobanzhang commented
> > emm 在 .NET 这个语言里我比较外行
> > 这个项目如果要在本地编辑 除了需要 .NET 的开发环境以外 还需要什么特殊的要求吗 比如 `特殊的控件` 或者 `特殊的 IDLE/开发环境` 什么的
> > ~主要龙猫没写开发环境和方式，我这个外行很心虚啊~
> 
> 没有……（我觉得这个也没啥必要在 readme 写很详细……

好嘞

2022-10-11 05:56 UTC, z0z0r4 commented
先声明，我是来找茬的
莫名越看越不爽，说不出的透出优越感，什么目录之类，画大饼之前能不能
![image](https://user-images.githubusercontent.com/78744121/195004391-334fa3a8-ffcb-4c54-a58f-5ec199db9737.png)
看完整个 Conversation，总感觉你才是龙猫，此 Readme.md 所有者
![image](https://user-images.githubusercontent.com/78744121/195004923-c35c6eea-df48-48d2-a8ba-952045a77113.png)
看完你的主页，现在我知道，你想变成所有者
不知道为啥 Github 可以把别人的项目 Pinned 在自己的主页上，起码不觉得你有资格挂着

以下是逐渐浓烈的不适感
![image](https://user-images.githubusercontent.com/78744121/195005864-f085ab49-5473-43ba-b213-4d13b0d45d81.png)
看完此仓库的 Readme 我脑子里只有无语，实在是看不出有啥值得你在写 Readme 方面课骄傲的，除了一坨全是个位数甚至0的标签和冗杂的待拍摄？尴尬死
![image](https://user-images.githubusercontent.com/78744121/195006234-05289c84-354a-4d5f-b5ec-80b27ab2b378.png)

2022-10-11 12:50 UTC, liubanlaobanzhang commented
> 先声明，我是来找茬的
> 莫名越看越不爽，说不出的透出优越感，什么目录之类，画大饼之前能不能
> ![image](https://user-images.githubusercontent.com/78744121/195004391-334fa3a8-ffcb-4c54-a58f-5ec199db9737.png)
> 看完整个 Conversation，总感觉你才是龙猫，此 Readme.md 所有者
> ![image](https://user-images.githubusercontent.com/78744121/195004923-c35c6eea-df48-48d2-a8ba-952045a77113.png)
> 看完你的主页，现在我知道，你想变成所有者
> 不知道为啥 Github 可以把别人的项目 Pinned 在自己的主页上，起码不觉得你有资格挂着
> 
> 以下是逐渐浓烈的不适感
> ![image](https://user-images.githubusercontent.com/78744121/195005864-f085ab49-5473-43ba-b213-4d13b0d45d81.png)
> 看完此仓库的 Readme 我脑子里只有无语，实在是看不出有啥值得你在写 Readme 方面课骄傲的，除了一坨全是个位数甚至0的标签和冗杂的待拍摄？尴尬死
> ![image](https://user-images.githubusercontent.com/78744121/195006234-05289c84-354a-4d5f-b5ec-80b27ab2b378.png)

# 不想搞什么优越感
# 只是为了方便而已
# 我的 Github.com 上面显示不出来最近的PR活动
# 也没什么人来看主页 就挂上 Pin 了

然后也仅仅是学习过一类的东西
如果不舒服的话就关这个 PR 了
我也不想惹事

2022-10-11 12:54 UTC, liubanlaobanzhang commented
我不想把 PR 搞成一个吵架的地方

我虚心接受您的意见
莫名的优越感现在想想是有的 我道歉

想来美化是真的 在.NET技术上我帮不了忙
但还是想为这个项目尽一份力
所以才有了这个 PR

我先关掉这个 PR
等过段日子如果可以的话
再来说吧

2022-10-11 12:54 UTC, closed without merging

2022-10-12 07:39 UTC, LTCatt commented
叹气，祝你之后好运吧（

2022-10-14 16:56 UTC, liubanlaobanzhang commented
> 叹气，祝你之后好运吧（

嘿嘿 我又回来了
在最近的小测中找了点信心
分析了一下之前的问题
打算搞个好一点的 不过尊重龙猫选择走简约风

现在已经在 VSCode 上面准备了
（等完工之后再交PR吧 免得被骂画饼）

2022-10-29 01:49 UTC, z0z0r4 commented
学习过关于 Readme 的正确书写...？算了，难蚌
> 也没什么人来看主页 就挂上 Pin 了

反正没人看这个 comment，我就评价一句：嘴硬

2022-10-29 17:16 UTC, XiaoMouz commented on README.md
> +- 此次 Readme 修改由[@老班长](https://github.com/liubanlaobanzhang)发起 (#191)，Github 社区伙伴用❤共同协作构建 (#193)。
不知道为什么，看到这里我的头突然就发晕了，很奇怪

2022-11-26 11:48 UTC, lvjiajjjlzy commented
瞎jb改

2023-05-03 01:57 UTC, iPodtouch6557 commented
~你原来是青岛人好嘛我也是但是我住在无锡~

2023-05-03 16:55 UTC, Chiloven945 commented
> 瞎jb改

把你最丑的毛病改改再来出人头地