添加 JVM 参数
Hex-Dragon/PCL2 pull request #3530
Opened 2024-03-16 04:34 UTC by wuliaodexiaoluo

# 3511

2024-03-16 05:20 UTC, allMagicNB commented
额，可以先想好再 Commit……
龙猫之后应该会做个判断啥的，所以这个 Pull request 除非龙猫不打算做判断，要不然很有可能不会被通过……

2024-03-16 05:29 UTC, wuliaodexiaoluo commented
> 额，可以先想好再 Commit…… 龙猫之后应该会做个判断啥的，所以这个 Pull request 除非龙猫不打算做判断，要不然很有可能不会被通过……

没有必要，因为 Issue 说的相当清楚，你可以回去看下

## 原话
经过证明添加此参数不会出现 OpenJ9 运行原版 Minecraft 加载本地地图时出现内存溢出错误，且暂时没有发现添加参数后对
Hotspot 虚拟机造成任何影响

因为这个参数几乎不会对 Hotspot 造成任何影响，直接 merge 没啥问题
加个判断符会增加代码复杂度

2024-03-16 05:38 UTC, LTCatt approved these changes

2024-03-19 07:16 UTC, zkitefly commented on Plain Craft Launcher 2/FormMain.xaml.vb
> +        'End If
？

2024-03-19 10:33 UTC, allMagicNB commented on Plain Craft Launcher 2/FormMain.xaml.vb
> +        'End If
这改了啥玩意？

2024-03-19 10:42 UTC, burningtnt commented on Plain Craft Launcher 2/FormMain.xaml.vb
> +        'End If
估计是不小心加了一堆空格

2024-03-19 10:46 UTC, allMagicNB requested changes
把那个注释里的 End If 搞回原样吧……

2024-03-19 10:50 UTC, Deep-Dark-Forest commented on Plain Craft Launcher 2/FormMain.xaml.vb
> +        'End If
～龙猫真是粗心（～

2024-03-20 00:42 UTC, wuliaodexiaoluo commented
稍等，马上改

2024-03-20 01:25 UTC, zkitefly approved these changes

2024-03-20 02:53 UTC, wuliaodexiaoluo commented on Plain Craft Launcher 2/FormMain.xaml.vb
> +        'End If
但事实上我没有给 End If 加任何字符
这应当是 GitHub Web Editor 的 Bug

2024-03-20 02:57 UTC, wuliaodexiaoluo reviewed
我是不是该应该建个 patch 而不是从 Main 直接合并

2024-03-20 02:58 UTC, JingHai-Lingyun commented
或许你该在本地改好了之后统一提交
~~我的邮箱开始信息++~~

2024-03-20 03:10 UTC, zkitefly commented
> 我是不是该应该建个 patch 而不是从 Main 直接合并

没关系d

2024-03-20 03:46 UTC, wuliaodexiaoluo commented
> 或许你该在本地改好了之后统一提交 ~我的邮箱开始信息++~

但是我不会用 Git 提交代码。。。。。
我连 GitHub Desktop 都用不明白

2024-03-22 15:41 UTC, hejiehao commented
> > 或许你该在本地改好了之后统一提交 ~我的邮箱开始信息++~
> 
> 但是我不会用 Git 提交代码。。。。。 我连 GitHub Desktop 都用不明白

一顿 `git commit` 然后再来一个 `git push`

2024-03-23 00:46 UTC, wuliaodexiaoluo commented
> > > 或许你该在本地改好了之后统一提交 ~我的邮箱开始信息++~
> > 
> > 
> > 但是我不会用 Git 提交代码。。。。。 我连 GitHub Desktop 都用不明白
> 
> 一顿 `git commit` 然后再来一个 `git push`

会不了一点，给个教程可以吗

2024-03-23 05:49 UTC, rumengchuxing062 approved these changes

2024-03-23 12:50 UTC, hejiehao commented
> > > > 或许你该在本地改好了之后统一提交 ~我的邮箱开始信息++~
> > > 
> > > 
> > > 但是我不会用 Git 提交代码。。。。。 我连 GitHub Desktop 都用不明白
> > 
> > 
> > 一顿 `git commit` 然后再来一个 `git push`
> 
> 会不了一点，给个教程可以吗

https://git-scm.com/doc

2024-03-23 20:52 UTC, LTCatt approved these changes

2024-04-05 14:14 UTC, merged