Create CONTRIBUTING.md
Hex-Dragon/PCL2 pull request #3564
Opened 2024-03-24 09:28 UTC by Silverteal

受到 steve-xmh/scl 和 #3487 的启发，设置贡献指引

2024-03-24 09:32 UTC, MCSteve123 commented
emm，以我的认知这不一定会过……看看情况

2024-03-24 10:28 UTC, zkitefly commented
加个同意pcl用户协议？

2024-03-24 10:30 UTC, allMagicNB requested changes
改下大小写（

2024-03-24 10:41 UTC, hejiehao commented on CONTRIBUTING.md
> +欢迎您对此仓库做出贡献。但是基于现实情况，您此时对此仓库提交 Pull Request （以下简称“PR”）即代表：
![71a766a729e48f7051bc116a8a596f13](https://github.com/Hex-Dragon/PCL2/assets/98140773/74c7adea-e2db-4ca5-b091-397f55a4fa7a)
![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/490f37fa-44f7-4971-abad-31e61c0c7602)
🤔

2024-03-24 10:45 UTC, burningtnt commented on CONTRIBUTING.md
> +欢迎您对此仓库做出贡献。但是基于现实情况，您此时对此仓库提交 Pull Request （以下简称“PR”）即代表：
![image](https://github.com/Hex-Dragon/PCL2/assets/88144530/2edcd618-6a3d-495c-ab5c-6a4440305138)

GitHub 自己都不太统一……

2024-03-24 10:49 UTC, hejiehao commented on CONTRIBUTING.md
> +`我已阅读 CONTRIBUTING.md 版本 1.0 并同意其中内容`
```suggestion
`我已阅读 CONTRIBUTING.md 1.0 版本并同意其中内容`  
```

2024-03-24 11:03 UTC, youzi-2333 commented on CONTRIBUTING.md
> +`我已阅读 CONTRIBUTING.md 版本 1.0 并同意其中内容`
说实话，（个人意见）我感觉版本号没啥必要………

2024-03-24 11:20 UTC, Silverteal commented
> 加个同意pcl用户协议？

和contribute本身无关吧？

2024-03-24 11:23 UTC, Silverteal commented on CONTRIBUTING.md
> +`我已阅读 CONTRIBUTING.md 版本 1.0 并同意其中内容`
这里用作约定文本，为了确保约定没有歧义，故添加了版本号

2024-03-24 14:13 UTC, Deep-Dark-Forest commented
我强烈介意将Ln7的``我已阅读 CONTRIBUTING.md 版本 1.0 并同意其中内容``改为` ```
我已阅读 CONTRIBUTING.md 版本 1.0 并同意其中内容
``` `

2024-03-25 10:06 UTC, dargoncat commented
说实话我感觉加这东西没必要.jpeg

2024-03-25 10:29 UTC, iPodtouch6557 commented
> 说实话我感觉加这东西没必要.jpeg

主要还是一些申明类似的，但是要是加了还不如也给issue搞一个

2024-03-26 01:47 UTC, dargoncat requested changes
你要真想整好歹在readme里面放个链接

2024-03-26 08:55 UTC, closed without merging

2024-03-26 08:55 UTC, LTCatt commented
感觉……意义不大……
本来就没有啥 PR，目前情况下还没有必要引入更多流程，保持简单就行 :)

2024-06-22 12:47 UTC, Deep-Dark-Forest commented
@LTCatt 目前本仓库 PR 数量已经逐渐增多，是否考虑一下此 PR（

2024-06-22 12:56 UTC, Silverteal commented
此PR的文本目前已不再适合当前的情况和新的LICENSE。
而且我原分支都删掉了怎么合并啊...

2024-06-22 12:58 UTC, JingHai-Lingyun commented
此 Pull Request 的上游分支被删除，Reopen 功能不可用。
如果需要，请重新制作

2024-06-22 13:07 UTC, Deep-Dark-Forest commented
> 此 PR 的文本已不再适合当前的情况和新的 LICENSE。

新的 LICENSE 中似乎未以任何方式提及到 PR。