fix #3591
Hex-Dragon/PCL2 pull request #3593
Opened 2024-04-01 15:02 UTC by allMagicNB

第一次交 Pull request，不知道有没有漏啥（
愚人节版本的说明感觉还可以再改改（

2024-04-01 15:14 UTC, scattered-leaves commented
介绍文本或许简洁点更好：
恭喜你朋友，你是个有毒的土豆

2024-04-01 15:21 UTC, allMagicNB commented
> 介绍文本或许简洁点更好：
> 恭喜你朋友，你是个有毒的土豆
> 

没事，每条说明都基本这么长，而且我这已经是以官网介绍的原话再翻译再简化的了（

2024-04-02 05:02 UTC, allMagicNB commented
第一次交 Pull request，不知道有没有漏啥（
愚人节版本的说明感觉还可以再改改（

2024-04-02 05:32 UTC, allMagicNB commented
参考文献：https://www.minecraft.net/zh-hans/article/poisonous-potato-update

2024-04-02 06:05 UTC, scattered-leaves commented
感觉还不如之前的介绍

2024-04-02 06:54 UTC, wuliaodexiaoluo requested changes
有种微软翻译的味道，并且感觉。。。。没有之前的好

2024-04-02 09:17 UTC, LTCatt approved these changes

2024-04-02 10:55 UTC, allMagicNB commented
> 有种微软翻译的味道，并且感觉。。。。没有之前的好

之前的是文献的开头，没用关于这次更新的任何信息

2024-04-03 00:35 UTC, wuliaodexiaoluo approved these changes

2024-04-03 07:47 UTC, zkitefly commented
![Screenshot_2024-04-03-15-47-05-90_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/Hex-Dragon/PCL2/assets/64117916/13533f6b-c0be-4ba4-a33b-079933baf64e)

你指定错了吧

2024-04-03 17:26 UTC, merged