修复#3840
Hex-Dragon/PCL2 pull request #3850
Opened 2024-05-18 13:45 UTC by xiaoliyuanpp

简单修了一下，只是图一个玩开源社区的乐趣罢了

2024-05-19 04:14 UTC, xiaoliyuanpp commented on Plain Craft Launcher 2/Pages/PageLaunch/MySkin.xaml.vb
> +                            {"Cherry Blossom", "樱花披风"}, {"15th Anniversary", "Minecraft 15周年纪念披风"}
感觉好，又感觉不好

2024-05-19 04:15 UTC, JingHai-Lingyun commented on Plain Craft Launcher 2/Pages/PageLaunch/MySkin.xaml.vb
> +                            {"Cherry Blossom", "樱花披风"}, {"15th Anniversary", "Minecraft 15周年纪念披风"}
按照（约定俗成的）规范来讲中文和英文/数字中间是要空一格的

2024-05-19 04:21 UTC, allMagicNB commented on Plain Craft Launcher 2/Pages/PageLaunch/MySkin.xaml.vb
> +                            {"Cherry Blossom", "樱花披风"}, {"15th Anniversary", "Minecraft 15周年纪念披风"}
官方中文名中间就有空格

2024-05-19 04:24 UTC, allMagicNB requested changes

2024-05-19 04:24 UTC, allMagicNB commented on Plain Craft Launcher 2/Pages/PageLaunch/MySkin.xaml.vb
> +                            {"Cherry Blossom", "樱花披风"}, {"15th Anniversary", "Minecraft 15周年纪念披风"}
```suggestion
                            {"Cherry Blossom", "樱花披风"}, {"15th Anniversary", "15 周年纪念披风"}
```
官方名没有 `Minecraft`

2024-05-19 04:28 UTC, xiaoliyuanpp commented on Plain Craft Launcher 2/Pages/PageLaunch/MySkin.xaml.vb
> +                            {"Cherry Blossom", "樱花披风"}, {"15th Anniversary", "Minecraft 15周年纪念披风"}
那就按官方的来吧

2024-05-19 11:31 UTC, xiaoliyuanpp commented
龙猫快点处理

2024-05-19 12:38 UTC, LTCatt requested changes
请按照社区的建议修改

2024-05-19 12:40 UTC, allMagicNB commented
不是，你说着改咋还没改反倒叫龙猫快点通过呢？

2024-05-19 12:49 UTC, allMagicNB commented
算了，我来

2024-05-20 11:05 UTC, xiaoliyuanpp commented
改好了
不太会用GitHub，不知道在哪里把pr里其他人修改的代码合并进来

2024-05-20 11:50 UTC, allMagicNB commented
不推荐使用中文作为标题和主题，这会导致 GitHub 无法自动匹配链接的项……

2024-05-20 11:56 UTC, xiaoliyuanpp commented
标题改了

2024-05-20 11:57 UTC, allMagicNB commented
> 标题改了

提交和主题改了才有用啊

2024-05-21 08:49 UTC, LTCatt approved these changes

2024-05-21 10:27 UTC, zkitefly approved these changes

2024-05-21 10:42 UTC, Deep-Dark-Forest approved these changes

2024-05-21 10:51 UTC, allMagicNB approved these changes

2024-05-22 11:25 UTC, wuyuncheng-26 approved these changes

2024-05-22 21:00 UTC, merged

2024-06-11 08:20 UTC, xiaoliyuanpp commented
怎么获取活跃橙啊

2024-06-11 10:47 UTC, Deep-Dark-Forest commented
> 
> 
> 
> 怎么获取活跃橙啊

您只能在**帮助库**中提交PR或者在此仓库提交bug并被处理完成才能获取活跃橙

2024-06-11 12:15 UTC, LTCatt commented
这里交 PR 也可以，我下个版本补上

2024-06-11 12:22 UTC, allMagicNB commented
完了我高血压了，叫人改改半天都没改好反而催起龙猫了，急的我都想自己来修了，而且这修复也没啥质量，就复制粘贴再仿照着改改……

2024-06-11 14:56 UTC, Deep-Dark-Forest commented
@xiaoliyuanpp 在 更多 → 关于与鸣谢 中点击复制识别码，并且发送到这里就能获取活跃橙了！

2024-06-12 13:02 UTC, xiaoliyuanpp commented
其实我也高血压，因为我不会用😭

2024-06-15 03:27 UTC, xiaoliyuanpp commented
抱歉哈，给你们（指开发组成员）添麻烦了

2024-06-15 03:31 UTC, allMagicNB commented
> 抱歉哈，给你们（指开发组成员）添麻烦了

其实并不是开发组（
开发者只有龙猫一个人，咱是社区贡献者（

2024-06-17 04:12 UTC, xiaoliyuanpp commented
识别码：6F8B-83E7-26FF-0815

2024-06-17 08:18 UTC, LTCatt commented
你的解锁码：dBUVeHG4PPW29TIo6eWBHW9qB3T2BsfT
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～