添加 Follower's Cape 的翻译
Hex-Dragon/PCL2 pull request #3885
Opened 2024-05-23 11:59 UTC by wuyuncheng-26

2024-05-23 12:17 UTC, LTCatt commented
你们要加一次加完吧求求了……别我把这个 merge 了又冒出来一个，挤牙膏呢

2024-05-23 12:28 UTC, wuyuncheng-26 commented
啊 对不起对不起

2024-05-25 04:10 UTC, Deep-Dark-Forest requested changes

2024-05-25 04:10 UTC, Deep-Dark-Forest commented on Plain Craft Launcher 2/Pages/PageLaunch/MySkin.xaml.vb
> +                            {"Cherry Blossom", "樱花披风"}, {"15th Anniversary", "15 周年纪念披风"}, {"Purple Heart", "紫色心形披风"}, {"Follower's Cape"，"追随者披风"}
不出意外的话，这里应该没有“Cape”？

2024-05-25 04:15 UTC, Deep-Dark-Forest commented
额龙猫为啥现在是“等待反馈者”？现在最近添加的三个披风都已经有PR汉化完了（

2024-05-25 04:28 UTC, allMagicNB commented on Plain Craft Launcher 2/Pages/PageLaunch/MySkin.xaml.vb
> +                            {"Cherry Blossom", "樱花披风"}, {"15th Anniversary", "15 周年纪念披风"}, {"Purple Heart", "紫色心形披风"}, {"Follower's Cape"，"追随者披风"}
你要不要先看看 Minecraft Wiki？

2024-05-25 04:54 UTC, wuyuncheng-26 commented on Plain Craft Launcher 2/Pages/PageLaunch/MySkin.xaml.vb
> +                            {"Cherry Blossom", "樱花披风"}, {"15th Anniversary", "15 周年纪念披风"}, {"Purple Heart", "紫色心形披风"}, {"Follower's Cape"，"追随者披风"}
我是看 wiki 的

2024-05-25 04:57 UTC, wuyuncheng-26 commented on Plain Craft Launcher 2/Pages/PageLaunch/MySkin.xaml.vb
> +                            {"Cherry Blossom", "樱花披风"}, {"15th Anniversary", "15 周年纪念披风"}, {"Purple Heart", "紫色心形披风"}, {"Follower's Cape"，"追随者披风"}
![IMG_5916](https://github.com/Hex-Dragon/PCL2/assets/122529705/4b9fb9b7-1389-4fb9-9a4b-df8bbc295603)
TBD: to be decided
应该是还没定下来

2024-05-25 05:03 UTC, wuyuncheng-26 commented
这个 PR 先搁置吧，官方还没有定下 Java 版 API 名称
https://minecraft.wiki/w/Cape#Cross-platform_capes

2024-05-25 05:08 UTC, Deep-Dark-Forest commented on Plain Craft Launcher 2/Pages/PageLaunch/MySkin.xaml.vb
> +                            {"Cherry Blossom", "樱花披风"}, {"15th Anniversary", "15 周年纪念披风"}, {"Purple Heart", "紫色心形披风"}, {"Follower's Cape"，"追随者披风"}
> 你要不要先看看 Minecraft Wiki？

6，Minecraft Wiki里面的迁移者披风是Migrator cape，minecon2016披风是MINECON 2016 Cape，15周年披风是15th Anniversary Cape，PCL代码里面都不是这些

2024-05-25 05:10 UTC, allMagicNB commented on Plain Craft Launcher 2/Pages/PageLaunch/MySkin.xaml.vb
> +                            {"Cherry Blossom", "樱花披风"}, {"15th Anniversary", "15 周年纪念披风"}, {"Purple Heart", "紫色心形披风"}, {"Follower's Cape"，"追随者披风"}
总之先等等

2024-05-25 05:14 UTC, wuyuncheng-26 commented on Plain Craft Launcher 2/Pages/PageLaunch/MySkin.xaml.vb
> +                            {"Cherry Blossom", "樱花披风"}, {"15th Anniversary", "15 周年纪念披风"}, {"Purple Heart", "紫色心形披风"}, {"Follower's Cape"，"追随者披风"}
> > 你要不要先看看 Minecraft Wiki？
> 
> 6，Minecraft Wiki里面的迁移者披风是Migrator cape，minecon2016披风是MINECON 2016 Cape，15周年披风是15th Anniversary Cape，PCL代码里面都不是这些，都不带最后面的“Cape”

应当以 Java Edition API Name 为准

2024-05-25 05:20 UTC, wuyuncheng-26 commented
我这边先删去 `Cape` 吧

2024-06-11 14:54 UTC, wuyuncheng-26 commented
官方开始测试了
https://zh-cn.namemc.com/cape/6dfe9599aa000ffc

2024-06-11 14:56 UTC, wuyuncheng-26 commented
目前来看 这个披风叫 Follower's

2024-06-11 15:33 UTC, wuyuncheng-26 commented
已修改

2024-06-11 21:59 UTC, allMagicNB requested changes

2024-06-11 21:59 UTC, allMagicNB commented on Plain Craft Launcher 2/Pages/PageLaunch/MySkin.xaml.vb
> +                            {"Cherry Blossom", "樱花披风"}, {"15th Anniversary", "15 周年纪念披风"}, {"Purple Heart", "紫色心形披风"}, {"Follower's"，"追随者披风"}
```suggestion
                            {"Cherry Blossom", "樱花披风"}, {"15th Anniversary", "15 周年纪念披风"}, {"Purple Heart", "紫色心形披风"}, {"Follower’s"，"追随者披风"}
```

2024-06-11 23:34 UTC, wuyuncheng-26 commented
done

2024-07-01 14:20 UTC, merged

2024-07-02 01:21 UTC, Light-Beacon commented on Plain Craft Launcher 2/Pages/PageLaunch/MySkin.xaml.vb
> +                            {"Cherry Blossom", "樱花披风"}, {"15th Anniversary", "15 周年纪念披风"}, {"Purple Heart", "紫色心形披风"}, {"Follower's"，"追随者披风"}
这对对对.....对吗？不是 `'` 吗？

2024-07-02 01:25 UTC, Light-Beacon commented on Plain Craft Launcher 2/Pages/PageLaunch/MySkin.xaml.vb
> +                            {"Cherry Blossom", "樱花披风"}, {"15th Anniversary", "15 周年纪念披风"}, {"Purple Heart", "紫色心形披风"}, {"Follower’s"，"追随者披风"}
这玩意用的就是 `'` 而不是 `’`，需要改回去（
@LTCatt

2024-07-02 04:00 UTC, Deep-Dark-Forest commented on Plain Craft Launcher 2/Pages/PageLaunch/MySkin.xaml.vb
> +                            {"Cherry Blossom", "樱花披风"}, {"15th Anniversary", "15 周年纪念披风"}, {"Purple Heart", "紫色心形披风"}, {"Follower’s"，"追随者披风"}
> 这玩意用的就是 `'` 而不是 `’`，需要改回去（ @LTCatt

#4138

2024-07-02 10:06 UTC, wuyuncheng-26 commented
？！

2024-07-02 10:25 UTC, wuyuncheng-26 commented on Plain Craft Launcher 2/Pages/PageLaunch/MySkin.xaml.vb
> +                            {"Cherry Blossom", "樱花披风"}, {"15th Anniversary", "15 周年纪念披风"}, {"Purple Heart", "紫色心形披风"}, {"Follower’s"，"追随者披风"}
超级难绷的 也不知道是哪位提的 review（暗示

2024-07-02 13:37 UTC, LTCatt commented
……我没有这个披风所以没法测试，那到底是哪个 orz

2024-07-02 13:39 UTC, wuyuncheng-26 commented
orz 那没办法了 有谁有披风愿意帮忙测试一下吗

2024-07-02 13:41 UTC, Light-Beacon commented
> ……我没有这个披风所以没法测试，那到底是哪个 orz

就是`'`这个垂直的，没有任何斜度的，在ascii码里的单引号XD

2024-07-02 14:49 UTC, allMagicNB commented
反正现在没事了，我拿我号测试了下，是 `Follower's`。