Auto build
Hex-Dragon/PCL2 pull request #3921
Opened 2024-05-28 22:03 UTC by allMagicNB

Fix #1451 
要在仓库里边加俩 Secret，我看看能不能去掉这环节，不进行签名
一个是 Base64_Encoded_Pfx，具体内容为 Pfx 签名证书的 Base64 编码
一个是 Pfx_Key，具体内容为上文的证书的密码

2024-05-28 22:20 UTC, allMagicNB commented
已删掉模板自带的签名部分

2024-05-29 05:10 UTC, zkitefly commented
建议将冗余的注释移除

2024-05-29 05:13 UTC, zkitefly requested changes

2024-05-29 05:13 UTC, zkitefly commented on .github/workflows/dotnet-desktop.yml
> +    branches: [ "Auto-Build" ]
`Auto-Build` ➡️ `main`

2024-05-29 05:18 UTC, zkitefly requested changes

2024-05-29 05:18 UTC, zkitefly commented on .github/workflows/dotnet-desktop.yml
> +name: .NET Core Desktop
名字要不换换？

2024-05-29 05:18 UTC, zkitefly commented on README.md
> +[![.NET Core Desktop](https://github.com/allMagicNB/PCL2/actions/workflows/dotnet-desktop.yml/badge.svg?branch=Auto-Build)](https://github.com/allMagicNB/PCL2/actions/workflows/dotnet-desktop.yml)
`Auto-Build` ➡️ `main`

`allMagicNB` ➡️ `Hex-Dragon`

2024-05-29 05:25 UTC, allMagicNB commented on README.md
> +[![.NET Core Desktop](https://github.com/allMagicNB/PCL2/actions/workflows/dotnet-desktop.yml/badge.svg?branch=Auto-Build)](https://github.com/allMagicNB/PCL2/actions/workflows/dotnet-desktop.yml)
这是为了测试用的，龙猫批准后我再改……

2024-05-29 05:39 UTC, zkitefly commented
workflows 的名称要不改改？

2024-05-29 05:54 UTC, zkitefly commented
branches 就不设置了吧

2024-05-29 07:46 UTC, LTCatt requested changes

2024-05-29 07:46 UTC, LTCatt commented on README.md
> +[![.NET Core Desktop](https://github.com/allMagicNB/PCL2/actions/workflows/dotnet-desktop.yml/badge.svg?branch=Auto-Build)](https://github.com/allMagicNB/PCL2/actions/workflows/dotnet-desktop.yml)
感觉最好不要加这个 badge……这可能会误导人觉得这是程序下载的地方 =。=

2024-05-29 07:46 UTC, LTCatt commented on .github/workflows/dotnet-desktop.yml
> +      run: dotnet test
没有 unit test，这应该没有卵用

2024-05-29 10:44 UTC, Deep-Dark-Forest commented on README.md
> +[![.NET Core Desktop](https://github.com/allMagicNB/PCL2/actions/workflows/dotnet-desktop.yml/badge.svg?branch=Auto-Build)](https://github.com/allMagicNB/PCL2/actions/workflows/dotnet-desktop.yml)
我感觉可以把文字改成 “开源版” ？

2024-05-29 10:53 UTC, allMagicNB commented
等会我改改，先去恰个饭

2024-05-29 11:42 UTC, allMagicNB commented
缩短运行所需时长，2~5 mins -> 1~2 min(s)

2024-05-29 12:25 UTC, LTCatt commented on README.md
> +[![.NET Core Desktop](https://github.com/allMagicNB/PCL2/actions/workflows/dotnet-desktop.yml/badge.svg?branch=Auto-Build)](https://github.com/allMagicNB/PCL2/actions/workflows/dotnet-desktop.yml)
它没有必要做下载，这只是为了方便社区调试用的

2024-05-29 12:27 UTC, allMagicNB commented on README.md
> +[![.NET Core Desktop](https://github.com/allMagicNB/PCL2/actions/workflows/dotnet-desktop.yml/badge.svg?branch=Auto-Build)](https://github.com/allMagicNB/PCL2/actions/workflows/dotnet-desktop.yml)
> 它没有必要做下载，这只是为了方便社区调试用的

那我删了（

2024-05-29 16:24 UTC, LTCatt requested changes

2024-05-29 16:24 UTC, LTCatt commented on README.md
> +![.NET Core Desktop](https://github.com/Hex-Dragon/PCL2/actions/workflows/dotnet-desktop.yml/badge.svg)
……这是啥玩意儿

2024-05-29 20:56 UTC, allMagicNB commented on README.md
> +![.NET Core Desktop](https://github.com/Hex-Dragon/PCL2/actions/workflows/dotnet-desktop.yml/badge.svg)
> ……这是啥玩意儿

就是换了下图片链接换成主仓库的，因为还没 Merge 所以就暂时还没图片（

2024-05-29 21:00 UTC, allMagicNB commented
把 README.md 里边的 Badge 换成了现在仓库的，去掉了点击打开链接（

2024-05-29 21:00 UTC, allMagicNB commented
@LTCatt

2024-05-29 21:12 UTC, allMagicNB commented
Merge 后那图片才会出来（

2024-05-30 07:28 UTC, LTCatt requested changes

2024-05-30 07:28 UTC, LTCatt commented on README.md
> +![.NET Core Desktop](https://github.com/Hex-Dragon/PCL2/actions/workflows/dotnet-desktop.yml/badge.svg)
但真的没必要加这个 badge……除了会有误导性以为这是程序下载地以外也没用啊……

2024-05-30 11:10 UTC, allMagicNB commented
那彳亍 口巴，我删 Badge 了（

2024-05-30 21:23 UTC, LTCatt approved these changes

2024-05-30 21:23 UTC, merged