#3780 重新提交
Hex-Dragon/PCL2 pull request #3945
Opened 2024-06-01 04:00 UTC by Silverteal

之前的pr #3780 因为误操作被关闭了 现在重新提交

2024-06-01 04:07 UTC, allMagicNB commented
为啥会编译出错……

2024-06-01 07:20 UTC, allMagicNB commented
先关了，我试试能不能 Reopen

2024-06-01 07:21 UTC, allMagicNB commented
好吧不能（

2024-06-01 07:21 UTC, JingHai-Lingyun commented
……？

2024-07-01 10:29 UTC, MCSteve123 commented
不是哥们咋还failing呢

2024-07-04 03:13 UTC, wuliaodexiaoluo commented on Plain Craft Launcher 2/Pages/PageDownload/PageDownloadClient.xaml.vb
> +                        Select Case Version("releaseDate").Value(Of Date).ToString("MM'/'dd")
改成 releaseTime ，没有 releaseDate，写这个会空值报错

2024-07-04 03:15 UTC, wuliaodexiaoluo requested changes
修下问题点

2024-07-04 03:15 UTC, wuliaodexiaoluo commented on Plain Craft Launcher 2/Pages/PageDownload/PageDownloadClient.xaml.vb
> +                        Select Case Version("releaseDate").Value(Of Date).ToString("MM'/'dd")
releaseTime

2024-07-04 03:15 UTC, wuliaodexiaoluo commented on Plain Craft Launcher 2/Pages/PageDownload/PageDownloadClient.xaml.vb
> +                                If Not Version("type") == "special" Then
== 不是 VB 表达法，VB 判断条件是否等于某个值是 if a = b Then

2024-07-04 03:16 UTC, wuliaodexiaoluo requested changes

2024-07-04 03:16 UTC, wuliaodexiaoluo commented on Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
> +                        Select Case Version("releaseDate").Value(Of Date).ToString("MM'/'dd")
同上哈

2024-07-04 03:16 UTC, wuliaodexiaoluo commented on Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
> +                                If Not Version("type") == "special" Then
这个也是

2024-07-04 03:32 UTC, wuliaodexiaoluo commented
这边等下 https://github.com/Silverteal/PCL2/pull/11 合并再合并
@Silverteal

2024-07-05 00:21 UTC, wuliaodexiaoluo requested changes

2024-07-05 00:21 UTC, wuliaodexiaoluo commented on Plain Craft Launcher 2/Pages/PageDownload/PageDownloadClient.xaml.vb
> +                                If Not Version("type") == "special" Then
改成 =

2024-07-05 00:21 UTC, wuliaodexiaoluo commented on Plain Craft Launcher 2/Pages/PageDownload/PageDownloadClient.xaml.vb
> +                        Select Case Version("releaseDate").Value(Of Date).ToString("MM'/'dd")
releaseTime

2024-07-05 00:21 UTC, wuliaodexiaoluo commented on Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
> +                        Select Case Version("releaseDate").Value(Of Date).ToString("MM'/'dd")
这段同上

2024-07-05 00:21 UTC, wuliaodexiaoluo commented on Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
> +                                If Not Version("type") == "special" Then
还是同上

2024-07-05 05:11 UTC, SALTWOOD requested changes
两处编译错误，两处逻辑错误。

2024-07-05 05:11 UTC, SALTWOOD commented on Plain Craft Launcher 2/Pages/PageDownload/PageDownloadClient.xaml.vb
> +                                If Not Version("type") == "special" Then
改成 =

2024-07-05 05:11 UTC, SALTWOOD commented on Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
> +                                If Not Version("type") == "special" Then
VB 是单等号比较，不是双等号

2024-07-05 05:11 UTC, SALTWOOD commented on Plain Craft Launcher 2/Pages/PageDownload/PageDownloadClient.xaml.vb
> +                        Select Case Version("releaseDate").Value(Of Date).ToString("MM'/'dd")
Time

2024-07-06 03:33 UTC, wuliaodexiaoluo commented on Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
> +                                If Not Version("type") == "special" Then
py 写多了可能

2024-07-12 00:14 UTC, wuliaodexiaoluo approved these changes

2024-07-28 21:45 UTC, merged

2024-08-09 06:02 UTC, hejiehao commented
![image](https://github.com/user-attachments/assets/6c5e98ed-63fb-45ab-86e0-c4b6eed08f53)
应该使用 Mojang 提供的原始时间而不是转换过后的时间

2024-08-09 06:15 UTC, JingHai-Lingyun commented
修补代码 于 #4449