重构编译工作流文件
Hex-Dragon/PCL2 pull request #4009
Opened 2024-06-11 22:06 UTC by allMagicNB

我个人认为并没有必要要多一个友好名称……
增加上传文件名带提交 Short Hash 值，然后……先等等吧，看看有没啥好的意见，可以去#3987 或下方 Comment，我觉得能做的话会加进#3987 里面，然后把此 PR 标记为 Draft。

2024-06-12 04:35 UTC, allMagicNB commented on .github/workflows/build.yml
> +        name: ${{ matrix.configuration }} ${{ env.Hash }}
I thought so at the beginning, but wanted to model the release package naming format (like 'Release 2.7.4').

2024-06-12 05:00 UTC, allMagicNB commented on .github/workflows/build.yml
> +        name: ${{ matrix.configuration }} ${{ env.Hash }}
> > I thought so at the beginning, but wanted to model the release package naming format (like 'Release 2.7.4').
> 
> I even forgot about this. So can we hear LTCatt’s thoughts?

So let's wait first.

2024-06-12 05:06 UTC, allMagicNB commented on .github/workflows/build.yml
> +        name: ${{ matrix.configuration }} ${{ env.Hash }}
But I think the Configuration is more important, and you can also use the file finder (e.g. Everything), or put them in a separate folder.

2024-06-12 07:44 UTC, LTCatt commented
你也没必要把人家的注释都删了吧……

2024-06-12 08:04 UTC, Silverteal commented
下次在有相同主题的PR还Open的时候，建议优先给那个PR的分支发PR，这样不用处理冲突……

2024-06-12 11:26 UTC, allMagicNB commented
> 下次在有相同主题的PR还Open的时候，建议优先给那个PR的分支发PR，这样不用处理冲突……

你说得不对，因为那样直接合并的话你的成果就废了。

2024-06-12 11:29 UTC, allMagicNB commented
> 你也没必要把人家的注释都删了吧……

这是重构，只不过文件名部分代码重复了而已（

2024-06-12 14:14 UTC, allMagicNB commented
@3gf8jv4dv How about looking at the file name now?

2024-06-12 14:22 UTC, allMagicNB commented
> _By the way, I have seen the format you wrote in other projects, but I just remembered it when I saw it just now, lol._

What? ~~I forgot.~~

2024-06-12 16:43 UTC, LTCatt requested changes
把一些不太废话的注释加回来吧……

2024-06-13 02:50 UTC, Silverteal commented
> > 下次在有相同主题的PR还Open的时候，建议优先给那个PR的分支发PR，这样不用处理冲突……
> 
> 你说得不对，因为那样直接合并的话你的成果就废了。

Git的文本引擎可以按行合并，而且您可以从分支的仓库拉取进行修改，这样就不会出现上述情况。

2024-06-13 11:26 UTC, allMagicNB commented
> 把一些不太废话的注释加回来吧……

没啥用。
工作流文件就只有五六十行，其中还有很多空行，相信懂 Action 怎么写的都能看懂，要加的话也得后期维护再多到一百多行再加，但是这不可能……

2024-06-13 11:32 UTC, LTCatt commented
把已有的注释给删了并没有让东西变得更好，并且也是对其他人的不尊重。不要这样做。

2024-06-13 11:33 UTC, allMagicNB commented
我没删我直接给重构的……

2024-06-13 11:36 UTC, LTCatt commented
唉，行吧……

2024-06-13 11:36 UTC, merged