NeoForge 支持
Hex-Dragon/PCL2 pull request #4045
Opened 2024-06-15 13:45 UTC by Pigeon0v0

本 PR 将基于先前的 Forge 安装流程，加入针对 NeoForge 的支持。
Close #2244 

To-Do List: 

- [x] 在自动安装界面加入 NeoForge 选项，并支持显示版本列表
- [ ] NeoForge 相关信息获取
- [ ] 版本列表相关处理（版本排序，NeoForge 相关信息显示，附加安装选项之间冲突等）
- [ ] NeoForge 自动安装（可能需要等待 Java Wrapper，我看看先）
- [ ] 相关资源文件（图标等）补充

如果在龙猫自己开始做支持之前这个 PR 还没有搞完，那就直接关了罢（

2024-06-15 15:03 UTC, SALTWOOD reviewed
看代码逻辑感觉没问题，期待

2024-06-15 15:27 UTC, Pigeon0v0 commented
> All are displayed as beta.
> 

Fix later.

2024-06-15 15:33 UTC, Pigeon0v0 commented
This comment(https://github.com/Hex-Dragon/PCL2/pull/4045/commits/655364b06a789308be699b0d3047b8f2bd961633) has not solved any problems. No need to test again. @3gf8jv4dv

2024-06-15 15:49 UTC, Pigeon0v0 commented
> Not sure if this will be implemented in this PR (I did not see it in the To-Do List).
> 
> NeoForge 20.5 renamed `mods.toml` to `neoforge.mods.toml`.
> 
> Currently only `mods.toml` is recognized in the `main` branch’s code.

This PR aims mainly at installing NeoForge. Related issues may be fixed another day.

2024-06-15 23:24 UTC, allMagicNB commented
~~不知道 Forge Installer 能不能用~~

2024-06-16 03:09 UTC, Pigeon0v0 commented
基本功能已经完成，剩下收个尾大概就可以合并了

手动安装这个版本列表我这里短时间搞不定，下周期末周，得等考完了再回来改

2024-06-16 03:32 UTC, SALTWOOD commented
图标有哪些需要？我来帮忙（

2024-06-16 03:38 UTC, SALTWOOD commented
> > 图标有哪些需要？我来帮忙（
> 
> At least two are required:
> 
> 1. The icon at _手动安装_ in the sidebar
> 2. The version list that appears after selecting NeoForge in _自动安装_
> 
> Preview

ok, I'm working on it.

2024-06-16 03:43 UTC, SALTWOOD commented
There are three possible alternative solutions:
![Sleeping_Baby_Fox](https://github.com/Hex-Dragon/PCL2/assets/105980161/e1a8ff27-f089-49d4-bf63-68c8259bbfe2)
![neoforged](https://github.com/Hex-Dragon/PCL2/assets/105980161/a04207a1-cf35-40c5-9bcd-00388d4d4e03)
![Baby_Fox_JE1_BE1](https://github.com/Hex-Dragon/PCL2/assets/105980161/d0ad0718-da33-484a-80ad-47e88efde0f0)

If someone has a better plan to propose

2024-06-16 05:07 UTC, Pigeon0v0 commented
Issues mentioned above will be handled later.

2024-06-16 05:22 UTC, SALTWOOD commented
As for the icon on the left side of the "Manual Installation" list, I chose a fox head as the icon. However, since the image is in color, I need to cut out the border. Is there anyone who can help me with that?
好的，那我应该会选用跟HMCL一样的图标。至于左侧“手动安装”列表的图标，我选择了狐狸的头像作为图标，但是因为图片是彩色的，我需要将它抠出边框来，有没有谁能帮我（

因为我看手动安装的列表里头，头像好看都是矢量的

![未标题-1](https://github.com/Hex-Dragon/PCL2/assets/105980161/b8e92edf-9e1d-4e72-94e0-a53ae77c1f91)

2024-06-16 05:27 UTC, SALTWOOD reviewed
感觉没啥问题……？也许可以比龙猫快完成

2024-06-16 05:27 UTC, SALTWOOD commented on Plain Craft Launcher 2/Pages/PageDownload/PageDownloadLeft.xaml
> +        <local:MyListItem x:Name="ItemNeoForge" Visibility="Collapsed" Type="RadioBox" IsScaleAnimationEnabled="False" Tag="13" MinPaddingRight="35" Height="36" VerticalAlignment="Top" Title="NeoForg
原来已经有了，当我没说（

2024-06-16 05:28 UTC, SALTWOOD commented
Action报错了，是不是没有内置资源？

2024-06-16 05:44 UTC, Pigeon0v0 commented
> After I selected a game version, the launcher froze…
> 

Caused by the icon. Trying to fix.

2024-06-16 07:47 UTC, Pigeon0v0 commented
> So fast! I will do detailed test later.

Thanks for your testing, but I'd like to note that the Manual Installing(手动安装) is still unavailable. For other possible issues, feel free to comment! :)

2024-06-16 08:22 UTC, Pigeon0v0 commented
> NeoForge cannot fetch list.

Fixed for mirror source, official one still doesn't work well. 

> In the 手动安装包 on the left column, the NeoForge icon is still the same as Forge.

Waiting for LTCatt.

2024-06-16 08:26 UTC, SALTWOOD commented
> > NeoForge cannot fetch list.
> 
> Fixed for mirror source, official one still doesn't work well. Need a vaild API Root.
> 
> > In the 手动安装包 on the left column, the NeoForge icon is still the same as Forge.
> 
> Waiting for LTCatt.

所以现在用的是镜像还是官方呢？

2024-06-16 08:34 UTC, SALTWOOD commented
ummm...... The mirror is already available in BMCLAPI. Are you going to add it?

2024-06-16 08:42 UTC, Pigeon0v0 commented
现在 BMCLAPI 和官方都加了，但是官方不太好使

2024-06-16 08:59 UTC, LTCatt commented
我在做下个版本的时候会 review，非常感谢，阿里嘎多

2024-06-16 10:21 UTC, zkitefly requested changes

2024-06-16 10:21 UTC, zkitefly commented on Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
> +            Result = NetGetCodeByDownload("https://maven.neoforged.net/api/maven/versions/releases/net/neoforged/neoforge", UseBrowserUserAgent:=True)
这个地址只会返回 1.20.1 以上的版本，并没有 1.20.1

1.20.1：`https://maven.neoforged.net/api/maven/versions/releases/net/neoforged/forge`

2024-06-16 10:26 UTC, zkitefly commented
1.20.1 以上：`https://maven.neoforged.net/releases/net/neoforged/neoforge/maven-metadata.xml`

1.20.1：`https://maven.neoforged.net/releases/net/neoforged/forge/maven-metadata.xml`

也可以试试这俩地址

2024-06-16 14:18 UTC, Pigeon0v0 commented
这俩没啥本质区别...依然不会返回支持的 MC 版本等信息，还得启动器自己判断

2024-06-17 02:19 UTC, Pigeon0v0 commented
f3079dd 没修干净，有空了改

2024-06-17 10:40 UTC, zkitefly commented
> 这俩没啥本质区别...依然不会返回支持的 MC 版本等信息，还得启动器自己判断

neoforge 版本号就有 mc 版本号的含义

2024-06-17 10:45 UTC, allMagicNB commented
NeoForge 版本号 a.b.c，对应的 Minecraft 小版本版本号一般为 1.a.b，如果是大版本那么就是 1.a。后面的 c 才是 NeoForge 自身的版本号

2024-06-17 10:45 UTC, WorldHim commented
> 这俩没啥本质区别...依然不会返回支持的 MC 版本等信息，还得启动器自己判断

NeoForge 的支持版本就写在版本号上😂
1.20.1 位于版本号最前面
1.20.1+ 只保留版本号后两个并加上  NeoForge 真实版本
e.g. `1.20.4` 对应 NeoForge `20.4.x`

2024-06-17 14:06 UTC, Pigeon0v0 commented
其实之前就看出来了，但是不是很敢确定（

2024-06-18 14:30 UTC, Pigeon0v0 commented
> 本 PR 将基于先前的 Forge 安装流程，加入针对 NeoForge 的支持。
> 
> Close #2244 
> 
> 
> 
> To-Do List: 
> 
> 
> 
> - [x] 在自动安装界面加入 NeoForge 选项，并支持显示版本列表
> 
> - [x] NeoForge 相关信息获取
> 
> - [x] 版本列表相关处理（版本排序，NeoForge 相关信息显示，附加安装选项之间冲突等）
> 
> - [x] NeoForge 自动安装
> 
> - [x] NeoForge 手动安装界面
> 
> - [x] 相关资源文件（图标等）补充
> 
> - [x] NeoForge 整合包安装
> 
> - [x] 其他界面选项和文本补充
> 
> 
> 
> Known Issues:
> 
> - （To be fixed）手动安装界面版本列表不能正常加载
> 
> - （To be fixed）官方源版本列表无法获取
> 
> - 左侧栏图标需要绘制
> 
> - （To be fixed）部分 1.20.1 NeoForge 整合包无法安装

2024-06-20 14:26 UTC, SALTWOOD reviewed
测试了没啥问题，但发现几处疑似显示错误？

2024-06-20 14:26 UTC, SALTWOOD commented on Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
> +        End Property
问一下这里是复制 Forge 部分留下的东西吗？看起来没啥用的亚子（

2024-06-20 14:26 UTC, SALTWOOD commented on Plain Craft Launcher 2/Modules/Minecraft/ModModpack.vb
> +                    Log(ex, "读取整合包 Forge 版本失败：" & Id)
这里忘改了？

2024-06-20 14:26 UTC, SALTWOOD commented on Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
> +            If MyMsgBox("该 Forge 版本过于古老，PCL 暂不支持该版本的自动安装。" & vbCrLf &
这里好像也是忘改了？后面几行也是写的 Forge

2024-06-20 15:09 UTC, Pigeon0v0 commented on Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
> +        End Property
是，改天改

2024-06-20 15:09 UTC, Pigeon0v0 commented on Plain Craft Launcher 2/Modules/Minecraft/ModModpack.vb
> +                    Log(ex, "读取整合包 Forge 版本失败：" & Id)
yep

2024-06-20 15:10 UTC, Pigeon0v0 commented on Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
> +            If MyMsgBox("该 Forge 版本过于古老，PCL 暂不支持该版本的自动安装。" & vbCrLf &
一起修

2024-06-21 08:41 UTC, Pigeon0v0 commented
除了官方源版本列表和手动安装列表还未修复以外，上文提到的整合包和部分文本问题已经修了，并且进行了代码清理。

各位可以再测试看看。

2024-06-21 09:18 UTC, Pigeon0v0 commented
> Some 1.20.1 NeoForge modpacks install with this error.
> 
> [_Log_](https://gist.github.com/3gf8jv4dv/da38723e0114ebe30a73b84d07a861f6).

It seems that it was a network issue, please try again?

2024-06-21 09:34 UTC, Pigeon0v0 commented
> Tried again, same result.

Any screenshots? I don't see any errors related to NeoForge installation in previous log.

2024-06-21 09:44 UTC, Pigeon0v0 commented
Fine. I'll check later.

2024-06-21 15:14 UTC, Pigeon0v0 commented
> Some 1.20.1 NeoForge modpacks install with this error.
> 
> [_Log_](https://gist.github.com/3gf8jv4dv/da38723e0114ebe30a73b84d07a861f6).

Fixed in 3bc3416

2024-06-21 16:25 UTC, Pigeon0v0 commented
@3gf8jv4dv 

70a6b6a should solve it.

2024-06-21 18:26 UTC, JingHai-Lingyun commented
晚点我看看 Icon 咋弄吧，NeoForge 那边说是没有官方的这个风格的 Icon 
I may trying to make an icon later. NeoForge Team said that they don't have a offical icon in this style
https://github.com/neoforged/NeoForge/discussions/1155#discussioncomment-9841845

2024-06-22 00:47 UTC, Pigeon0v0 commented
Issues mentioned above resolved in 61ac627 . 

Please test again and leave comments if there are any other issues. @3gf8jv4dv

2024-06-24 12:22 UTC, Tianpao512 commented
图标可以换成这个   https://neoforged.net/img/authors/neoforged.png

2024-06-26 01:33 UTC, Chiloven945 commented
这是modrinth目前使用的neoforge图标
<img width="103" alt="image" src="https://github.com/Hex-Dragon/PCL2/assets/116699482/56069f61-e220-48ab-bdcc-2325b58e21c7">
除此之外个人觉得neoforge的游戏版本图标还有待商榷，始终会有突兀的感觉……

2024-06-26 13:29 UTC, Pigeon0v0 commented
3f5c292 enables to parse the version list from the official source. However, the version list in Manual Installing still has some problems. I'll deal with them later.

2024-06-26 14:14 UTC, Pigeon0v0 commented
The issue of the version list in Manual Installing has been resolved in 707b6ee.

2024-06-26 15:56 UTC, Pigeon0v0 commented
> My side always fallback to BMCLAPI.
> 

Fixed in ee10caa.

2024-06-27 00:05 UTC, Pigeon0v0 commented
> Still the same error.
> 

Fixed again in ac6ed8d. 

This build should be fine.

2024-06-27 03:42 UTC, Pigeon0v0 commented
目前看来功能运行都没问题了，可以直接合，但是部分代码是真的一坨...

请求 Review 的时候优化一下 & 轻点喷...

@LTCatt

2024-06-27 06:13 UTC, Pigeon0v0 commented
> Other versions are good, 1.20.1 NeoForge still the same error.
> 

Fixed in 1b53489. 

Note: The 1.20.1 version list from the official source will put 47.1.82 in the first place incorrectly. This is a known issue but I have no good idea for this. Waiting for LTCatt to refactor sorting.

2024-06-27 10:09 UTC, LTCatt requested changes

2024-06-27 10:09 UTC, LTCatt commented on Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
> +                    "https://maven.neoforged.net/releases/net/neoforged/neoforge/" & DownloadInfo.StdVersion & If(DownloadInfo.IsBeta, "-beta", "") & "/" & DownloadInfo.FileName
考虑内插字符串

2024-06-27 10:09 UTC, LTCatt commented on Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
> +                Dim JavaLoader = JavaFixLoaders(17)
可能需要确认它具体支持的 Java 版本。Forge 支持 Java 8u60 及更高版本，但 NeoForge 可能不同。

2024-06-27 10:09 UTC, LTCatt commented on Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
> +    Private Sub NeoForgeInjectorLine(Content As String, Task As LoaderTask(Of Boolean, Boolean))
如果与 Forge 完全一致，考虑直接使用 Forge 的对应函数？

2024-06-27 10:09 UTC, LTCatt commented on Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
> +    Private Sub NeoForgeInjector(Target As String, Task As LoaderTask(Of Boolean, Boolean), McFolder As String, UseJavaWrapper As Boolean)
如果与 Forge 完全一致，考虑直接使用 Forge 的对应函数？

2024-06-27 10:09 UTC, LTCatt commented on Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
> +                    "https://maven.neoforged.net/releases/net/neoforged/neoforge/" & DownloadInfo.StdVersion & If(DownloadInfo.IsBeta, "-beta", "") & "/" & DownloadInfo.FileName
考虑内插字符串

2024-06-27 10:09 UTC, LTCatt commented on Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
> +    Private Function McDownloadNeoForgeLoader(Version As String, Inherit As String, Optional DownloadRawInfo As DlNeoForgeVersionEntry = Nothing, Optional McFolder As String = Nothing, Optional Clien
如果这个函数与 Forge 大体相同，可以考虑合并到一起，增加一个参数来判断是 Forge 还是 NeoForge？

2024-06-27 10:09 UTC, LTCatt commented on Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
> +#Region "NeoForge 下载菜单"
同样地，考虑和 Forge 进行合并，直接并到一个 Region 下面？

2024-06-27 10:09 UTC, LTCatt commented on Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
> +        If PathTemp.Contains(" ") AndAlso (Request.ForgeEntry IsNot Nothing Or Request.NeoForgeEntry IsNot Nothing) Then
使用 OrElse 而非 Or，由于它会在左侧为 true 时不计算右侧表达式，性能更好。

2024-06-27 10:18 UTC, Pigeon0v0 commented on Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
> +            If Not (ClientVersionString.ContainsF("a") OrElse ClientVersionString.ContainsF("b") OrElse ClientVersionString.ContainsF("c") OrElse ClientVersionString.ContainsF("w") OrElse ClientVersi
因为不会写正则所以...（

改

2024-06-27 10:19 UTC, Pigeon0v0 commented on Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
> +        Next
能加 API 最好，因为现在没有这个 API（

2024-06-27 10:19 UTC, Pigeon0v0 commented on Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
> +        Public Category As String
可能是冗余的

2024-06-27 10:20 UTC, Pigeon0v0 commented on Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
> +        Public FileSuffix As String = "jar"
看起来是只有 Jar

2024-06-27 10:20 UTC, Pigeon0v0 commented on Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
> +                Inherit = Inherit.Replace(".0", "")
👌

2024-06-27 10:21 UTC, Pigeon0v0 commented on Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
> +                        ElseIf RealJson.Contains("neoforge") Then    '1.20.1 NeoForge Json 内信息不同，为了方便直接截断 orgeVersion；这里的实现比较抽象，正则我写不会
那就留着你改吧，正则我之前鼓捣了好长一段时间真的头大...

2024-06-27 10:22 UTC, Pigeon0v0 commented on Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
> +                Dim JavaLoader = JavaFixLoaders(17)
会进行相关测试

2024-06-27 10:24 UTC, Pigeon0v0 commented on Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
> +    Private Sub NeoForgeInjector(Target As String, Task As LoaderTask(Of Boolean, Boolean), McFolder As String, UseJavaWrapper As Boolean)
这里抽出来我觉得比较好，主要是方便日后 NeoForge 如果改了啥能直接改，而不必动 Forge

2024-06-27 11:32 UTC, Pigeon0v0 commented on Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
> +    Private Function McDownloadNeoForgeLoader(Version As String, Inherit As String, Optional DownloadRawInfo As DlNeoForgeVersionEntry = Nothing, Optional McFolder As String = Nothing, Optional Clien
同样觉得可以方便日后修改（

2024-06-27 11:40 UTC, Pigeon0v0 commented on Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
> +                End If
这个地方不知道为什么去重不了一点，用 Distinct 的话手动安装界面就是超级重复...

2024-06-27 11:48 UTC, Pigeon0v0 commented
以上标记为 Resolved 的 Reviews 都解决了，可以再看看？

2024-06-27 21:17 UTC, LTCatt requested changes
中间还有几条（

2024-06-27 21:17 UTC, LTCatt commented on Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
> +                End If
`Versions = Versions.Distinct().ToList()` 这样？

2024-06-27 21:17 UTC, LTCatt commented on Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
> +        Next
我问下 @bangbang93 ……
能不能给这俩文件加个 API 缓存？
https://maven.neoforged.net/api/maven/versions/releases/net/neoforged/neoforge
https://maven.neoforged.net/api/maven/versions/releases/net/neoforged/forge

2024-06-27 21:17 UTC, LTCatt commented on Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
> +    Private Sub NeoForgeInjector(Target As String, Task As LoaderTask(Of Boolean, Boolean), McFolder As String, UseJavaWrapper As Boolean)
安装器部分的第三方更改其实都很少，但如果 PCL 这边的代码出了 bug，重复代码容易导致修了一边但另一边没修……所以目前还是以少出现重复代码为主 Orz

2024-06-28 01:47 UTC, Pigeon0v0 commented on Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
> +#Region "NeoForge 下载菜单"
这里涉及好多控件和虚拟化的东西，有点头大...Orz

2024-06-28 01:50 UTC, Pigeon0v0 commented
cf43244 合并了 Forge 和 NeoForge 部分代码，我个人测试下来功能貌似没啥毛病...

Neo 下载菜单那边我有点搞不太动了，控件虚拟化太头大了...

2024-06-28 01:53 UTC, bangbang93 commented
我想再了解一下，要这俩列表的本质是要什么，因为连mc版本都没确定的话，拿到这个大列表我觉得好像没什么太大用？

2024-06-28 02:04 UTC, Pigeon0v0 commented
> 我想再了解一下，要这俩列表的本质是要什么，因为连mc版本都没确定的话，拿到这个大列表我觉得好像没什么太大用？

结尾 `neoforge` 的列表会返回所有 Latest NeoForge，其版本号本身就提供了支持的 MC 版本信息

结尾 `forge` 的列表只会返回 Legacy NeoForge，其只支持 1.20.1

2024-06-28 02:12 UTC, bangbang93 commented
所以最终不还是要先确定mc版本号吗？

2024-06-28 02:23 UTC, Pigeon0v0 commented
> 所以最终不还是要先确定mc版本号吗？ 在什么case下需要不分版本的展示所有neoforge？

主要是为了判断支持的 MC 版本需要...

如果 BMCLAPI 可以直接返回一个这个列表就也可以了其实（

2024-06-28 02:30 UTC, bangbang93 commented
我觉得neoforge这个版本号规则是在给自己埋坑……你们要的话我就这两天把这个API也缓存一下好了

2024-06-28 03:29 UTC, Pigeon0v0 commented
> 我觉得neoforge这个版本号规则是在给自己埋坑……你们要的话我就这两天把这个API也缓存一下好了

感谢（

2024-06-28 08:02 UTC, LTCatt requested changes

2024-06-28 08:02 UTC, LTCatt commented on Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
> +            Version = DownloadInfo.VersionCode
```vb
If IsNeo Then
    If DownloadNeoInfo Is Nothing Then
    Else
    End If
Else 'Forge
End If
```
用这个格式逻辑会更清晰一点……？

2024-06-28 08:02 UTC, LTCatt commented on Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
> +        Dim InstallerAddress As String = PathTemp & $"Cache\Code\{If(IsNeo, "Neo", "")}ForgeInstall-" & Version & "_" & RandomInteger(0, 100000)
同样建议提前确定 NeoForge/Forge 字符串作为变量，而非数次拼合

2024-06-28 08:02 UTC, LTCatt commented on Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
> +        McDownloadForgeSave(True, , Version)
使用 `McDownloadForgeSave(True, DownloadNeoInfo:=Version)`，不建议使用空逗号来跳过可选参数

2024-06-28 14:00 UTC, Pigeon0v0 commented
上面的改了

2024-06-29 04:50 UTC, bangbang93 commented
文档见<https://bmclapidoc.bangbang93.com/#api-Neoforge-NeoforgeMavenApi>
使用例
- `https://maven.neoforged.net/api/maven/details/releases/net/neoforged/neoforge` -> `https://bmclapi2.bangbang93.com/neoforge/meta/api/maven/details/releases/net/neoforged/neoforge`
- `https://maven.neoforged.net/api/maven/details/releases/net/neoforged/forge` -> `https://bmclapi2.bangbang93.com/neoforge/meta/api/maven/details/releases/net/neoforged/forge`

同时对应的子目录也有
- https://bmclapi2.bangbang93.com/neoforge/meta/api/maven/details/releases/net/neoforged/forge/1.20.1-47.1.5

2024-06-29 22:29 UTC, Pigeon0v0 commented
今天下午有空来修一下

2024-06-30 07:05 UTC, Pigeon0v0 commented
Issues mentioned by @3gf8jv4dv are resolved in 3c44a55. 

Meanwhile, the version list from BMCLAPI is using the new API now, working as expected. 

Feel free to test and leave comments :)

2024-06-30 07:08 UTC, Pigeon0v0 commented
主楼提到的版本列表和排序的事情麻烦看一下，对我来说有点难了...

其他的功能大概是没问题

Ping @LTCatt

2024-06-30 07:12 UTC, Pigeon0v0 commented
主楼提到的版本列表和排序的事情麻烦看一下，对我来说有点难了...

其他的功能大概是没问题

Ping @LTCatt

2024-06-30 09:05 UTC, LTCatt requested changes
https://github.com/Hex-Dragon/PCL2/pull/4045#discussion_r1656845113
这里往后还有几条……

琢磨了一下逻辑，现在似乎没有分两次加载（获取 MC 版本列表 → 获取特定版本下的全部版本列表）的必要，直接像 OptiFine 那样加载一次就行了，这样应该能大大加快加载，并且减少 API 消耗？

2024-06-30 09:05 UTC, LTCatt commented on Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
> +        Public Branch As String = Nothing
这些字段是不是从未使用过？

2024-06-30 09:12 UTC, Pigeon0v0 commented on Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
> +        Public Branch As String = Nothing
Hash 可能是必要的，因为看起来有些函数会要求 Hash...

其他两个从未使用过，会删除

2024-06-30 13:07 UTC, Pigeon0v0 commented
上面这俩提议我包是搞不动的...

歇一阵子再来，或者直接龙猫改了罢 Orz

2024-07-01 23:38 UTC, Pigeon0v0 commented
看起来是在准备发版了，如果这次打算加上的话大概是得龙猫自己修一下了...

2024-07-02 07:52 UTC, LTCatt commented
umm 还有哪些东西是没整完的，能帮忙列一下么，我到时候修了 =。=

2024-07-02 08:34 UTC, Pigeon0v0 commented
侧边栏图标；一次加载获取版本列表；1.20.1 的 NeoForge 版本列表有楼上的问题（主要是 47.1.82 和 BMCLAPI 源的 47.1.106 的问题）

2024-07-05 12:15 UTC, LTCatt commented
umm 能否提供使用 NeoForge 的 MCBBS、CurseForge、Modrinth 整合包以便测试？

2024-07-05 13:12 UTC, Pigeon0v0 commented
[NeoForge-20.4.237-HMCL.zip](https://github.com/user-attachments/files/16110116/NeoForge-20.4.237-HMCL.zip)
[NeoForge-20.4.237-BakaXL.zip](https://github.com/user-attachments/files/16110117/NeoForge-20.4.237-BakaXL.zip)

以上是我自己用其他启动器导出的...

要去找一个之前就有的包多半是有点吃力...

2024-07-05 14:03 UTC, merged

2024-07-05 14:03 UTC, LTCatt commented
剩下的我自己做了 =。=