尝试修复 1.8 和 1.9 的 Optifine 列表问题
Hex-Dragon/PCL2 pull request #4052
Opened 2024-06-16 10:11 UTC by Silverteal

据 OpenBMCLAPI 成员反馈，Optifine 的分版本列表中将 1.8 和 1.9 分别标记为（实际上是错误的） 1.8.0 和 1.9.0，导致安装整合包时可能无法正确下载上述两个版本的 Optifine。

此 PR 旨在尝试处理该问题，但具体的解决方式也没有经过严格测试，供参考。

2024-06-17 08:20 UTC, LTCatt commented
但会有整合包用 1.8 和 1.9 OptiFine 用来复现测试么……

2024-06-17 09:05 UTC, allMagicNB commented
> 但会有整合包用 1.8 和 1.9 OptiFine 用来复现测试么……

大不了自己造一个（

2024-06-17 09:32 UTC, LTCatt commented
……但如果现在没有，之后也不可能有人用 1.8 / 1.9 OptiFine 做整合包，那这个玩意儿就压根没意义啊

2024-06-17 09:35 UTC, allMagicNB commented
找到了
https://pan.baidu.com/share/link?shareid=3084269415&uk=4021218445&_at_=1718616924039

2024-07-11 08:41 UTC, LTCatt requested changes
`McDownloadOptiFine` 方法已未被使用，这个 PR 没有生效 =。=

2024-07-16 23:22 UTC, Silverteal commented
> `McDownloadOptiFine` 方法已未被使用，这个 PR 没有生效 =。=

那我投降┗( T﹏T )┛  
放着当issue好了

2024-07-17 05:30 UTC, LTCatt commented
交一个 issue 把这个 PR 关了吧

2024-07-17 05:42 UTC, closed without merging

2024-07-17 05:42 UTC, Silverteal commented
#4281

2024-08-09 07:21 UTC, allMagicNB commented
？@Deep-Dark-Forest 你乱加 Label

2024-08-09 07:24 UTC, JingHai-Lingyun commented
PR 被放弃了…… 应该……

2024-08-09 07:26 UTC, allMagicNB commented
> PR 被放弃了…… 应该……

你先去看看这个 Label 的说明先。

2024-08-09 07:26 UTC, Silverteal commented
可以没有 label 吗