为版本设置添加启动前内存优化
Hex-Dragon/PCL2 pull request #4058
Opened 2024-06-17 16:20 UTC by youzi-2333

检索式：`-label:"· Bug" 版本 AND 启动前 AND 内存 AND 优化`

命名一类问题以及 UI 问题请指出，感谢！

~如果不想加的话就关掉好了，只是我拿来复习一下 vb 用的（~

2024-06-17 18:47 UTC, LTCatt requested changes

2024-06-17 18:47 UTC, LTCatt commented on Plain Craft Launcher 2/Pages/PageVersion/PageVersionSetup.xaml.vb
> +
应当合并到 ComboChange 方法，添加一个 Handles

2024-06-17 18:47 UTC, LTCatt commented on Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
> +JumpRamOptimize:
这里可以不用 GoTo，合并进 Select Case？

2024-06-18 05:29 UTC, youzi-2333 commented on Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
> +JumpRamOptimize:
dc3804a √

2024-06-18 08:17 UTC, LTCatt approved these changes

2024-07-01 18:40 UTC, merged