为 Mod 列表、下载添加 MCLM 下载源
Hex-Dragon/PCL2 pull request #4291
Opened 2024-07-18 04:41 UTC by youzi-2333

如有问题请指出，感谢！@z0z0r4

2024-07-18 05:56 UTC, Pigeon0v0 commented
Close #4267（关联投票 #4270）

2024-07-18 06:18 UTC, z0z0r4 commented
正在预缓存 curseforge...避免上线后直接被打穿，除了文件下载部分欢迎尝试

2024-07-18 11:29 UTC, wuyuncheng-26 approved these changes
能做到稳定还是很难的（
不论如何，感谢 z0z0r4 提供的镜像源 orz

2024-07-19 09:55 UTC, z0z0r4 commented
意见征求：https://github.com/MCLF-CN/docs/issues/3#issuecomment-2238538065

2024-07-20 06:06 UTC, LTCatt approved these changes

2024-07-22 13:06 UTC, z0z0r4 commented
已经稳定上线了，接下来不会进行功能改动

@LTCatt 是说，大概得 delay 多久？多少希望能尽早合并，基本上如果返校了的话（8.1），还是比较难及时对过载等情况做出调整的...

尽管没多大可能会出现炸膛的情况，但还是比较担心=-= 由于没有任何数据可以作为参考，不跑起来真不知道
~~虽然我大概知道返校前是不可能看到更新合并了~~

2024-07-22 17:59 UTC, LTCatt commented
可能是月内。

2024-07-23 01:52 UTC, z0z0r4 commented
![741c7f099e5e18ed2207d71b236260ad](https://github.com/user-attachments/assets/02e7bf23-da79-47cb-ba82-8e5a54fc0a31)

2024-07-26 08:34 UTC, LTCatt requested changes

2024-07-26 08:34 UTC, LTCatt commented on Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml
> +                        <local:MySlider x:Name="SliderDownloadThread" Grid.Row="7" Tag="ToolDownloadThread" MaxValue="255" Value="63" Grid.Column="1"
![image](https://github.com/user-attachments/assets/a184a3e4-5f27-465e-8daa-d3edf9d1a624)
把这两个合并成类似 `版本列表获取` 这样的三选一下拉框吧……

2024-07-26 08:34 UTC, LTCatt commented on Plain Craft Launcher 2/Pages/PageDownload/PageDownloadMod.xaml
> +                <local:MyHint x:Name="HintError" Text="无法连接到 Modrinth，所以目前仅显示了来自 CurseForge 的内容，结果可能不全。&#xa;请尝试在 设置 → 启动器 → Mod 信息获取 中切换到镜像源，或者使用 VPN 或加速器以改善网络。" IsWarn="True" Margin="0,0,0,15" />
如果会在一个源失败时强制转另一个源，那么这个提示实际上就没有必要：无法连接的时候是两个源都连不上。

2024-07-26 08:34 UTC, LTCatt commented on Plain Craft Launcher 2/Pages/PageDownload/PageDownloadMod.xaml
> +                <local:MyHint x:Name="HintError" Text="无法连接到 Modrinth，所以目前仅显示了来自 CurseForge 的内容，结果可能不全。&#xa;请尝试在 设置 → 启动器 → Mod 信息获取 中切换到镜像源，或者使用 VPN 或加速器以改善网络。" IsWarn="True" Margin="0,0,0,15" />
并且这个信息是代码赋值的，改 xaml 没用（
https://github.com/Hex-Dragon/PCL2/blob/5bd8ac3870170b0acd4d81934227829f8e79ca84/Plain%20Craft%20Launcher%202/Pages/PageDownload/PageDownloadMod.xaml.vb#L51-L57

2024-07-26 08:34 UTC, LTCatt commented on Plain Craft Launcher 2/Modules/Base/ModNet.vb
> +        End Try
考虑换用 `NetGetCodeByDownload`，它的 URL 允许提供一个数组，这样可以在一个源寄了的时候自动切换到另一个 URL。
URL 获取可以加到这里：
https://github.com/Hex-Dragon/PCL2/blob/5bd8ac3870170b0acd4d81934227829f8e79ca84/Plain%20Craft%20Launcher%202/Modules/Minecraft/ModDownload.vb#L1096-L1102

2024-07-26 08:34 UTC, LTCatt commented on Plain Craft Launcher 2/Modules/Base/ModNet.vb
> +        End If
不太应该把这个特判加到所有东西通用的基础库函数里……

2024-07-26 14:40 UTC, youzi-2333 commented on Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml
> +                        <local:MySlider x:Name="SliderDownloadThread" Grid.Row="7" Tag="ToolDownloadThread" MaxValue="255" Value="63" Grid.Column="1"
umm 是这样的，那个复选框其实是专指 Mod **文件** 下载是否允许使用镜像源，具体原因如下图所示。

不知道龙猫怎么看……？

![image](https://github.com/user-attachments/assets/c5165c64-edae-435d-a0a9-7e9c4f364c08)

![image](https://github.com/user-attachments/assets/2e5a7edb-d218-4123-acef-8236cb7b107f)

2024-07-26 14:53 UTC, z0z0r4 commented on Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml
> +                        <local:MySlider x:Name="SliderDownloadThread" Grid.Row="7" Tag="ToolDownloadThread" MaxValue="255" Value="63" Grid.Column="1"
我是咋都不介意，只要策略不是 **可以选择 文件下载 强制走镜像源** 就行...

无论如何，文件下载都是备线

2024-07-26 16:55 UTC, LTCatt commented on Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml
> +                        <local:MySlider x:Name="SliderDownloadThread" Grid.Row="7" Tag="ToolDownloadThread" MaxValue="255" Value="63" Grid.Column="1"
我建议是设置只影响版本获取倾向，文件下载永远是源站优先、镜像源备用

2024-07-28 14:32 UTC, youzi-2333 commented
@LTCatt @z0z0r4 改的差不多了……整体逻辑参考了版本列表获取。

感谢！

2024-07-28 16:26 UTC, LTCatt requested changes

2024-07-28 16:26 UTC, LTCatt commented on Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
> +            TargetProject = New CompProject(If(FromCurseForge, comp("data"), comp))
……这是……在干什么……

2024-07-28 17:18 UTC, LTCatt commented on Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
> +        {"ToolDownloadModMirror", New SetupEntry(False, Source:=SetupSource.Registry)},
没删干净……？

2024-07-28 17:18 UTC, LTCatt commented on Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
> +                    Urls.Add(New KeyValuePair(Of String, Integer)(McimUrl, 60))
这里写的 Timeout 的单位是毫秒，也就是说你设了一个最长 60ms 就会超时的网络请求，这会导致所有请求都操作超时，根本跑不通一点。

2024-07-28 17:18 UTC, LTCatt commented on Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
> +            .Replace("staging-api.modrinth.com/v2", "mod.mcmirror.top/modrinth") _
这里 API 网址错了，应该是 mod.mcimirror.top 而非 mod.mcmirror.top

2024-07-28 17:18 UTC, LTCatt commented on Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
> +                Return NetGetCodeByDownload(url.Key, Timeout:=url.Value, IsJson:=IsJson)
这里应该用 NetGetCodeByRequestOnce，而非 NetGetCodeByDownload。
NetGetCodeByDownload 是多线程下载网页的特殊方法，不适合请求 API。

2024-07-28 17:18 UTC, LTCatt commented on Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
> +                    Urls.Add(New KeyValuePair(Of String, Integer)(McimUrl, 60))
这里的 Timeout 参数根本没传出去，所以设置选 1 和 2 根本没有区别（更何况设置项名字都错了）

2024-07-28 17:18 UTC, LTCatt commented on Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
> +            Select Case Setup.Get("ToolDownloadVersion")
这里应该是 ToolDownloadMod。也就是说你加的设置项一直都没生效……

2024-07-28 17:18 UTC, LTCatt commented on Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
> +
不必要的 Import。

2024-07-28 17:18 UTC, LTCatt commented on Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
> +                            Dim RequestResult As JObject = DlModRequest(CurseForgeUrl, IsJson:=True)
这里把 Encoding.UTF8 参数完全改没了，可能导致编码问题。

2024-07-28 17:18 UTC, LTCatt commented on Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
> +                TargetProject = New CompProject(DlModRequest("https://api.curseforge.com/v1/mods/" & ProjectId, IsJson:=True)("data"))
这里毫无意义地重复请求了两次 API，why？

2024-07-28 17:18 UTC, LTCatt commented on Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
> +                retryCount += 1
DlModRequest 已经具有备份请求的功能了（毕竟两个源），没有必要添加重试

2024-07-28 17:18 UTC, LTCatt commented on Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
> +            If comp Is Nothing Then '获取 ("data") 时会报值不能为 null
没搞懂这个写法的意义……

2024-07-28 17:18 UTC, LTCatt commented on Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
> +            TargetProject = New CompProject(If(FromCurseForge, comp("data"), comp))
前面刚设置了 TargetProject，然后又再设置一遍？！

2024-07-28 17:18 UTC, LTCatt commented
这些是我在合并的时候发现的问题……
说实话，这 bug 太多了点，很多地方根本都跑不通，例如 API 域名都写错了，还特喵设置了 30ms 的 timeout，真的让我怀疑这真有测试过吗？
最后我基本把整个 PR 全部重写了一遍……
希望之后至少先检查一下再交……合并的时候感觉像在玩扫雷……

上面的 Review 也不需要改了，我自己修完了 Orz

2024-07-28 23:21 UTC, youzi-2333 commented
ummm 昨天晚上太急了忘记测试了…………抱歉抱歉

2024-07-29 00:46 UTC, z0z0r4 commented
crazy，幸好我看不懂 VB 没看🫠

2024-08-11 19:08 UTC, merged