读取MCBBS整合包文件中的Jvm
Hex-Dragon/PCL2 pull request #4401
Opened 2024-08-03 13:16 UTC by tmdakm

2024-08-03 13:16 UTC, tmdakm commented
#4395

2024-08-03 13:23 UTC, allMagicNB commented
……你不会用 jObject？

2024-08-03 13:28 UTC, allMagicNB requested changes

2024-08-03 13:28 UTC, allMagicNB commented on Plain Craft Launcher 2/Modules/Minecraft/ModModpack.vb
> +            Dim javaArgument As String = String.Join(" ", launchInfo("javaArgument"))
```suggestion
            Dim launchArgument As String = String.Join(" ", Json("launchInfo")("launchArgument"))
            Dim javaArgument As String = String.Join(" ", Json("launchInfo")("javaArgument"))
```

不知道能不能用。

2024-08-03 13:29 UTC, tmdakm commented
> ……你不会用 jObject？

草

2024-08-03 13:48 UTC, tmdakm commented on Plain Craft Launcher 2/Modules/Minecraft/ModModpack.vb
> +            Dim javaArgument As String = String.Join(" ", launchInfo("javaArgument"))
[dff8a4](https://github.com/Hex-Dragon/PCL2/pull/4401/commits/53578a8de9bf1cfbb6a8d8e54f6015738cdff8a4)

2024-08-03 14:24 UTC, Pigeon0v0 commented
Close #4395

2024-08-03 16:59 UTC, LTCatt approved these changes

2024-08-12 19:50 UTC, LTCatt requested changes

2024-08-12 19:50 UTC, LTCatt commented on Plain Craft Launcher 2/Modules/Minecraft/ModModpack.vb
>          '构造加载器
缺少 End If。这个 PR 是不是从来没测试过？

2024-08-12 19:50 UTC, LTCatt commented on Plain Craft Launcher 2/Modules/Minecraft/ModModpack.vb
> +            Dim javaArgument As String = String.Join(" ", Json("launchInfo")("javaArgument"))
按这个写法，整合包的这个参数会完全覆盖 PCL 的默认 JVM 参数，这是预期行为吗……？

2024-08-13 00:17 UTC, allMagicNB commented on Plain Craft Launcher 2/Modules/Minecraft/ModModpack.vb
>          '构造加载器
包没测试的，漏了个引号都不知道。

2024-08-15 07:08 UTC, tmdakm commented on Plain Craft Launcher 2/Modules/Minecraft/ModModpack.vb
>          '构造加载器
把End If补上了 不知道为什么git提交上去的和我本地有点区别

2024-08-15 07:24 UTC, tmdakm commented on Plain Craft Launcher 2/Modules/Minecraft/ModModpack.vb
> +            Dim javaArgument As String = String.Join(" ", Json("launchInfo")("javaArgument"))
这个和对指定版本设置jvm参数头尾的效果是一样的，应该不会影响到默认的参数吧（
没理解这个默认JVM参数指的是啥

2024-08-15 16:08 UTC, LTCatt commented on Plain Craft Launcher 2/Modules/Minecraft/ModModpack.vb
> +            Dim javaArgument As String = String.Join(" ", Json("launchInfo")("javaArgument"))
![image](https://github.com/user-attachments/assets/aae58a4b-34dd-4902-a263-bb6514fae993)
它会不会覆盖掉这个设置（

2024-08-17 09:15 UTC, tmdakm commented on Plain Craft Launcher 2/Modules/Minecraft/ModModpack.vb
> +            Dim javaArgument As String = String.Join(" ", Json("launchInfo")("javaArgument"))
它覆盖的是正在安装的这个整合包版本的这个设置 因为是在安装的时候覆盖的 这个时候用户应该都无法修改这个设置才对吧（

2024-10-15 08:29 UTC, LTCatt commented
https://github.com/Hex-Dragon/PCL2/issues/4395#issuecomment-2413228902

2025-03-20 07:13 UTC, tmdakm commented
全新 视频 在 13cj 点 vip

2025-03-20 07:13 UTC, tmdakm commented
666我号出问题了

2025-03-20 07:24 UTC, tmdakm commented
可以无视这个request。刚刚我的账号被盗号者登录了并在这个pr下发布了违规言论，现在已经解决，打扰致歉

2025-05-29 15:08 UTC, merged

2025-06-16 18:44 UTC, tmdakm commented
~~要个活跃橙~~ B06B-F5E8-B3CA-ECEB

2025-06-16 18:54 UTC, LTCatt commented
你的解锁码：w8j+pBAHsdntt1cSWbEpMlM9hkCwPv6e
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～