新功能：简单的本地 Mod 筛选
Hex-Dragon/PCL2 pull request #4404
Opened 2024-08-04 15:26 UTC by tangge233

代码有点粗糙，还请多指导

Close #679

2024-08-04 15:59 UTC, JingHai-Lingyun commented
挺好 ~~，有人做了我想做的事~~。
看了眼 CI 构建的版本，提一点 UI 方面的建议：
1. 我觉得可以不用调换功能按钮与搜索框的位置
2. 如果全选时没有打开的卡片会给人一种类似 `虚空选择` 的感觉
3. 可以默认显示全部，然后给一个下拉框实现切换 Filter？

2024-08-04 16:25 UTC, tangge233 commented
如果用下拉框切换的话界面可能有点难看.jpg

2024-08-04 16:28 UTC, tangge233 commented on Plain Craft Launcher 2/Pages/PageVersion/PageVersionMod.xaml.vb
> +        InitializeComponent()
VisualStudio 自动加上了这个……

2024-08-04 17:19 UTC, LTCatt commented
![image](https://github.com/user-attachments/assets/94c6e21e-2755-4b6c-b995-2e9269ed4c96)
我想的是这样的……

因为 PR 的实现方法和我预想的完全不一样，所以先不检查了 orz

2024-08-05 00:59 UTC, tangge233 commented
好像需要首次加载过有缓存后，第二次才可以直接获取 Mod CanUpdate 情况
看来要改改（

2024-08-05 03:05 UTC, wuyuncheng-26 commented
> 好像需要首次加载过有缓存后，第二次才可以直接获取 Mod CanUpdate 情况 看来要改改（

测试了一下，确实是有这种情况的

2024-08-05 05:36 UTC, tangge233 commented
![image](https://github.com/user-attachments/assets/1759c6e8-5fc4-41c5-9f95-23bf276cffd1)
解决了奇奇怪怪的问题，同时较符合了龙猫的预期 :)
~~界面我不太会写，龙猫帮我~~

2024-08-05 06:05 UTC, tangge233 commented
> The number of mods that can be updated should not be added to the number of all mods.
> 
> The current behavior is, for example, if I have three mods and one mod can be updated, then the total number of mods will become four.

Oh,that was my mistake.I will fix it later.

2024-08-05 11:22 UTC, tangge233 commented
@LTCatt 弄好了，大概是你要的样子（
Have a look: https://github.com/tangge233/PCL2/actions/runs/10247847302/artifacts/1776002365

2024-08-05 11:54 UTC, tangge233 commented
> I have no other opinions at the moment.我目前没有其他意见。
> 
> Similar to the previous example, there are three mods, one disabled and one updatable. When we select the disabled or updatable label, only one mod will be shown in the list, but Ctrl+A will prompt that three mods are selected.与前面的示例类似，有三个模组，一个已禁用，一个可更新。当我们选择禁用或可更新的标签时，列表中只会显示一个模组，但 Ctrl+A 会提示已选择三个模组。
> 
> From the commit history, this seems to be intentional, but I personally feel that the logic is a bit strange.从提交历史来看，这似乎是有意为之，但我个人觉得逻辑有点奇怪。

Fixed. I was a bit too careless.

2024-08-05 15:18 UTC, LTCatt requested changes

2024-08-05 15:18 UTC, LTCatt commented on Plain Craft Launcher 2/Pages/PageVersion/PageVersionMod.xaml
> +                            <local:MyTextButton VerticalContentAlignment="Center" Height="20" Margin="3,0" Tag="Enabled" Text="已启用" x:Name="BtnTypeEnabled"/>
可以用 MyRadioButton，然后在这一堆的最左边添加一个“全部”并默认选中

2024-08-05 15:18 UTC, LTCatt commented on Plain Craft Launcher 2/Pages/PageVersion/PageVersionMod.xaml.vb
> +            Case "All"
加一个枚举

2024-08-05 20:10 UTC, LTCatt approved these changes

2024-08-06 12:33 UTC, MCSteve123 commented
> LTCatt 弄好了，大概是你要的样子（ Have a look: https://github.com/tangge233/PCL2/actions/runs/10247847302/artifacts/1776002365

不对啊，你这开源版本咋还显示快照版提示啊

2024-08-06 12:40 UTC, tangge233 commented
随机测试这么多次，应该不会再出问题了

2024-08-06 12:41 UTC, tangge233 commented
> > LTCatt 弄好了，大概是你要的样子（ Have a look: https://github.com/tangge233/PCL2/actions/runs/10247847302/artifacts/1776002365
> 
> 不对啊，你这开源版本咋还显示快照版提示啊

默认就这么显示，如有修改意见，可以 PR 或 Issue

2024-08-06 12:44 UTC, wuyuncheng-26 commented
> > LTCatt 弄好了，大概是你要的样子（ Have a look: https://github.com/tangge233/PCL2/actions/runs/10247847302/artifacts/1776002365
> 
> 不对啊，你这开源版本咋还显示快照版提示啊

~你是没用过开源版吗，本来就是这样的~
#4181

2024-08-07 03:00 UTC, MCSteve123 commented
> > > LTCatt 弄好了，大概是你要的样子（ Have a look: https://github.com/tangge233/PCL2/actions/runs/10247847302/artifacts/1776002365
> > 
> > 
> > 不对啊，你这开源版本咋还显示快照版提示啊
> 
> ~你是没用过开源版吗，本来就是这样的~ #4181

确实没用过，我不会写C#

2024-08-19 16:16 UTC, merged