支持 unlisted-versions-of-minecraft
Hex-Dragon/PCL2 pull request #4555
Opened 2024-08-20 03:40 UTC by zkitefly

Close #3786

2024-08-20 04:24 UTC, tangge233 commented on Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
> +            Trg = ""
```suggestion
            Dim Teg = ""
```

2024-08-20 04:38 UTC, youzi-2333 commented on Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
> +            Return Teg & "这个秘密计划了两年的更新将游戏推向了一个新高度！"
```suggestion
        If Name.StartsWith("2.0") OrElse Name.StartsWith("2point0") Then
            Dim Tag As String = ""
            If Name.StartsWith("red") Then
                Tag = "（红色版本）"
            ElseIf Name.StartsWith("blue") Then
                Tag = "（蓝色版本）"
            ElseIf Name.StartsWith("purple") Then
                Tag = "（紫色版本）"
            End If
            Return Tag & "这个秘密计划了两年的更新将游戏推向了一个新高度！"
```

2024-08-20 04:38 UTC, youzi-2333 commented on Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
> +                Replace("https://zkitefly.github.io/unlisted-versions-of-minecraft", "https://raw.gitcode.com/zkitefly/unlisted-versions-of-minecraft/raw/main"),
GitCode 会不会当作 abuse 封掉（？）

2024-08-20 04:38 UTC, youzi-2333 commented on Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
> +        If Entry("url").ToString.Contains("unlisted-versions-of-minecraft") Then NewItem.Info = "[UVMC 特供下载] " & NewItem.Info
有一个小 Bug（但是这部分代码我没看过，不知道在哪里出的问题）：`1_19_deep_dark_experimental_snapshot_1` 等二十多个版本被错误分到远古版。
<details>
<summary>截图</summary>
<img src="https://github.com/user-attachments/assets/ee7906aa-500d-45f2-a371-50dbe0f7b23f">
</details>

2024-08-20 04:39 UTC, zkitefly commented on Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
> +                Replace("https://zkitefly.github.io/unlisted-versions-of-minecraft", "https://raw.gitcode.com/zkitefly/unlisted-versions-of-minecraft/raw/main"),
应该不会，至少没发生过

2024-08-20 04:39 UTC, tangge233 commented on Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
> +                Replace("https://zkitefly.github.io/unlisted-versions-of-minecraft", "https://raw.gitcode.com/zkitefly/unlisted-versions-of-minecraft/raw/main"),
我们这移动把 github.io 全墙（

2024-08-20 04:47 UTC, zkitefly commented on Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
> +                Replace("https://zkitefly.github.io/unlisted-versions-of-minecraft", "https://raw.gitcode.com/zkitefly/unlisted-versions-of-minecraft/raw/main"),
代码逻辑似乎是先 github.io 再到 gitcode.com

2024-08-20 05:01 UTC, zkitefly commented on Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
> +        If Entry("url").ToString.Contains("unlisted-versions-of-minecraft") Then NewItem.Info = "[UVMC 特供下载] " & NewItem.Info
https://github.com/Hex-Dragon/PCL2/pull/4555/commits/9c5d2f0ed88e821c5974e2e80af5271e0d6475f1 ？

2024-08-20 05:28 UTC, tangge233 approved these changes

2024-08-20 05:39 UTC, tangge233 commented
![image](https://github.com/user-attachments/assets/1a55e128-8e3a-4f77-a547-71fcc62bcee2)
已下载好的版本归类不正确

2024-08-20 05:50 UTC, tangge233 commented on Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
> +            If Name.StartsWith("red") Then
emmmm，突然发现都是 Name.StartsWith 这里好像永远达不到……

2024-08-20 07:13 UTC, Deep-Dark-Forest commented on Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
> +                Replace("https://zkitefly.github.io/unlisted-versions-of-minecraft", "https://raw.gitcode.com/zkitefly/unlisted-versions-of-minecraft/raw/main"),
> GitCode 会不会当作 abuse 封掉（？）

这种事应该只会发生在 Gitee 上

2024-08-20 08:34 UTC, zkitefly commented on Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
> +            If Name.StartsWith("red") Then
改好了

2024-08-20 08:35 UTC, zkitefly commented
> ![image](https://private-user-images.githubusercontent.com/50769997/359349593-1a55e128-8e3a-4f77-a547-71fcc62bcee2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNDMxNTksIm5iZiI6MTcyNDE0Mjg1OSwicGF0aCI6Ii81MDc2OTk5Ny8zNTkzNDk1OTMtMWE1NWUxMjgtOGUzYS00Zjc3LWE1NDctNzFmY2M2MmJjZWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDA4MzQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4ODM1ZjMzNmY3YmJjYjIxZWFjZDY1NDE2NDU1N2I4ZGE5YjBkMjg0NTE2MTE4OWFlMDA3ZmE2MDMxMTIyNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WidpzgnTRdSSGLkfJjtG7IsysDPl63ufZB9r39O3n5E) 已下载好的版本归类不正确 还有这个 ![image](https://private-user-images.githubusercontent.com/50769997/359351162-8814ff6e-0d0e-4bd5-844c-fe9e44e5eba8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNDMxNTksIm5iZiI6MTcyNDE0Mjg1OSwicGF0aCI6Ii81MDc2OTk5Ny8zNTkzNTExNjItODgxNGZmNmUtMGQwZS00YmQ1LTg0NGMtZmU5ZTQ0ZTVlYmE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDA4MzQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkMmE0OTc5NGJlNmIzYjljYmJkNzhmZmZjOGVlODhkY2RmYTI1YjI1NzU2MGU1Y2JlOGJiMTE5YjNkOThmYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6WVKoqQXb6X0l2SzanxNM_xowISIGzuu_3eGFD6Sqaw)

![image](https://github.com/user-attachments/assets/8f38b8fa-72d5-4534-96a7-088e6e2658f6)

![image](https://github.com/user-attachments/assets/4b141f5f-9f11-49c7-aab2-42cc420ccc8f)

![image](https://github.com/user-attachments/assets/1464f06d-e21c-4492-9ac4-6cbb8f1cbd2f)

版本分类没问题了

2024-08-20 08:38 UTC, zkitefly commented
![image](https://github.com/user-attachments/assets/026eb355-5cdf-47d7-b4b0-d68b5e646b6d)

![image](https://github.com/user-attachments/assets/54e8cdad-0751-40e2-8d6d-abe3e251f765)

这要解决吗，好像不是本  PR 导致的？

2024-08-20 08:42 UTC, zkitefly commented
注：我将 更新日志 按钮跳转 Wiki 的链接替换为 `https://zh.minecraft.wiki/w/Special:%E6%90%9C%E7%B4%A2?search=`

这个链接搜索完全匹配的关键词时会直接跳转至相关页面，如果没有也会在搜索页展示匹配到的关键词

主要是远古版无论是 Wiki 还是版本 Id 都太乱了，搞昏了（

2024-08-20 08:44 UTC, zkitefly commented
将 远古版本 的时间判定改为 2000 年到 2011 年 9 月 20 日之间

2024-08-20 08:48 UTC, wuliaodexiaoluo commented
>这要解决吗，好像不是本 PR 导致的？
#4528

2024-08-20 08:54 UTC, youzi-2333 commented on Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
> +            Return Teg & "这个秘密计划了两年的更新将游戏推向了一个新高度！"
![image](https://github.com/user-attachments/assets/06de0332-9f54-43d2-a2ac-3a70adfae724)

将 `2point0` 替换为 `2.0` 也许会更好。

2024-08-20 09:46 UTC, zkitefly commented on Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
> +            Return Teg & "这个秘密计划了两年的更新将游戏推向了一个新高度！"
https://github.com/Hex-Dragon/PCL2/pull/4555/commits/a81b321388d8ba6dea421530997f1c4d9fa717e3

2024-08-20 11:54 UTC, tangge233 approved these changes

2024-08-20 12:22 UTC, Deep-Dark-Forest approved these changes

2024-08-20 13:20 UTC, youzi-2333 approved these changes

2024-08-25 06:47 UTC, zkitefly commented on Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
> +            Versions.Merge(UnlistedJson("versions"))
或许这些获取列表该加个 try 以防因为这个导致加载不了下载列表？

2024-08-27 02:46 UTC, wuyuncheng-26 approved these changes

2024-08-29 16:58 UTC, zkitefly commented on Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
> +            Versions.Merge(UnlistedJson("versions"))
https://github.com/Hex-Dragon/PCL2/pull/4555/commits/76d0f014d72ca538ba71e41141b0719d8586c357

2024-08-30 19:22 UTC, LTCatt requested changes

2024-08-30 19:22 UTC, LTCatt commented on Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
> +            End Try
考虑使用和 download.json 一样的优先使用缓存的方式，这样不会延长版本列表的加载时间，也不必每个下载源都请求一次文件

2024-08-30 19:22 UTC, LTCatt commented on Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
> +            Dim Teg = ""
Tag?

2024-08-30 19:22 UTC, LTCatt commented on Plain Craft Launcher 2/Pages/PageDownload/PageDownloadClient.xaml.vb
> +                            Not Version("id").ToString.ToLower.Contains("1.2") AndAlso
可能误判 1.20？

2024-08-30 19:22 UTC, LTCatt commented on Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
> +                            Not Version("id").ToString.ToLower.Contains("1.2") AndAlso
可能误判 1.20？

2024-08-31 00:03 UTC, zkitefly commented on Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
> +            Dim Teg = ""
https://github.com/Hex-Dragon/PCL2/pull/4555/commits/f4fb08559f59a7503fa072b1fa84a9de3f5e7a72

2024-08-31 00:15 UTC, zkitefly commented on Plain Craft Launcher 2/Pages/PageDownload/PageDownloadClient.xaml.vb
> +                            Not Version("id").ToString.ToLower.Contains("1.2") AndAlso
https://github.com/Hex-Dragon/PCL2/pull/4555/commits/c4b59de7806d17555477a4e794550dee5c5d5857

2024-08-31 00:15 UTC, zkitefly commented on Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
> +                            Not Version("id").ToString.ToLower.Contains("1.2") AndAlso
https://github.com/Hex-Dragon/PCL2/pull/4555/commits/c4b59de7806d17555477a4e794550dee5c5d5857

2024-08-31 00:52 UTC, zkitefly commented on Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
> +            End Try
https://github.com/Hex-Dragon/PCL2/pull/4555/commits/7965ca818d1d5bc0ec182df211c1824f45ee8c7e

2024-09-21 09:45 UTC, allMagicNB commented
![image](https://github.com/user-attachments/assets/c738ca44-e1b0-401b-96db-556d700e7d00)
byd，PR Collection 炸了我还以为是我解决冲突有问题，结果就是这个 PR 导致的

2024-09-21 10:28 UTC, allMagicNB commented
缓存策略的锅，之前来自 PCL CDN 的缓存没删掉，导致直接读了……

2024-09-21 11:07 UTC, allMagicNB requested changes

2024-09-21 11:07 UTC, allMagicNB commented on Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
> +            If File.Exists(CacheFilePath) Then
```suggestion
            Else '如果缓存文件存在，则将其读取并合并到版本列表中
```

2024-09-21 11:07 UTC, allMagicNB commented on Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
> +            If File.Exists(CacheFilePath) Then
```suggestion
            Else '如果缓存文件存在，则将其读取并合并到版本列表中
```

2024-09-21 11:42 UTC, allMagicNB approved these changes

2024-10-25 17:49 UTC, LTCatt commented on Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
> +        If Name.StartsWithF("2.0") OrElse Name.StartsWith("2point0") Then
```suggestion
        If Name.StartsWithF("2.0") OrElse Name.StartsWithF("2point0") Then
```

2024-10-25 17:50 UTC, zkitefly commented on Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
> +                        If ReleaseTime.Year > 2000 AndAlso (ReleaseTime.Year < 2011 OrElse (ReleaseTime.Year = 2011 AndAlso ReleaseTime.Month < 9) OrElse (ReleaseTime.Year = 2011 AndAlso ReleaseTime.
我在思考要改吗，有问题吗，有的话怎么搞（

2024-10-26 05:45 UTC, zkitefly commented on Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
> +                        If ReleaseTime.Year > 2000 AndAlso (ReleaseTime.Year < 2011 OrElse (ReleaseTime.Year = 2011 AndAlso ReleaseTime.Month < 9) OrElse (ReleaseTime.Year = 2011 AndAlso ReleaseTime.
谢谢❤️

2024-10-26 06:24 UTC, zkitefly commented
> https://github.com/zkitefly/unlisted-versions-of-minecraft
> 
> Upstream also needs to change to mark versions before 1.0.0 as old.
> 
> Other aspects LGTM.

这个标签是 version json 里头的，不是很像改（

2024-10-27 02:30 UTC, tangge233 requested changes
问题不大（）

2024-10-27 02:30 UTC, tangge233 commented on Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
> +                        If ReleaseTime.Year > 2000 AndAlso (ReleaseTime.Year < 2011 OrElse (ReleaseTime.Year = 2011 AndAlso ReleaseTime.Month < 11) OrElse (ReleaseTime.Year = 2011 AndAlso ReleaseTime
```suggestion
                        If ReleaseTime.Year > 2000 AndAlso ReleaseTime <= New DateTime(2011, 11, 16) Then ' 2000 年到 2011 年 11 月 16 日之间
```

2024-10-27 03:33 UTC, allMagicNB approved these changes

2024-11-23 01:38 UTC, zkitefly commented
![image](https://github.com/user-attachments/assets/f77d54db-652f-48e7-8f41-4220069793a1)

2025-01-25 09:00 UTC, zkitefly commented
打算是下游 CE 版测试没问题再来合并，而且这个 PR 已经搞乱了（

2025-01-25 09:00 UTC, closed without merging

2025-01-25 09:00 UTC, zkitefly commented
打算是下游 CE 版测试没问题再来合并，而且这个 PR 已经搞乱了（