MyImage 控件
Hex-Dragon/PCL2 pull request #4868
Opened 2024-10-01 15:14 UTC by tangge233

支持加载本地和在线 WebP 的图片控件，适配之后的帮助库图片格式变更

2024-10-01 19:19 UTC, LTCatt requested changes

2024-10-01 19:19 UTC, LTCatt commented on Plain Craft Launcher 2/Controls/MyImage.xaml
> +﻿<Border x:Class="MyImage"
最外层元素应该可以直接用 Image，不需要 Border 来额外框一下……？这样应该能优化一下性能……

2024-10-02 04:08 UTC, tangge233 commented
修改了下实现方式，支持 WebP 的同时支持使用 Base64 编码的图片

2024-10-02 07:04 UTC, tangge233 commented
## 还需修改
- 不清理图片缓存以帮助帮助库图片加载
- 没必要支持 base64（那玩意纯增加文件体积…）

2024-10-02 07:33 UTC, LTCatt requested changes

2024-10-02 07:33 UTC, LTCatt commented on Plain Craft Launcher 2/Modules/Base/MyBitmap.vb
> +                    Dim tempFile = PathTemp & "Cache\MyImage\" & GetHash(FilePathOrResourceName)
这是哪来的缓存……

2024-10-02 07:33 UTC, LTCatt commented on Plain Craft Launcher 2/Controls/MyImage.vb
> +            SetImage(value)
这个方法可以联立进来，直接放在这

2024-10-02 07:33 UTC, LTCatt commented on Plain Craft Launcher 2/Controls/MyImage.vb
> +    Public Uuid As Integer = GetUuid()
没有动画的控件不需要 UUID

2024-10-02 07:57 UTC, tangge233 commented on Plain Craft Launcher 2/Modules/Base/MyBitmap.vb
> +                    Dim tempFile = PathTemp & "Cache\MyImage\" & GetHash(FilePathOrResourceName)
_下面 NetDownload 下来的_

2024-10-02 08:47 UTC, LTCatt commented on Plain Craft Launcher 2/Modules/Base/MyBitmap.vb
> +                    Dim tempFile = PathTemp & "Cache\MyImage\" & GetHash(FilePathOrResourceName)
这不是一个好的实践，对于固定 URL 但图片动态变化的接口，这会导致一直“获取”到同一个图片。
目前没有什么在底层实现缓存的需求（Mod Logo 已经独立实现了缓存），直接将下载的文件读取不作缓存或许就行？

2024-10-02 08:52 UTC, tangge233 commented on Plain Craft Launcher 2/Modules/Base/MyBitmap.vb
> +                    Dim tempFile = PathTemp & "Cache\MyImage\" & GetHash(FilePathOrResourceName)
这个实际上每次重新建立 MyImage 都会重新下载，本地缓存只是方便 WebP 格式文件处理……

2024-10-02 09:04 UTC, tangge233 commented on Plain Craft Launcher 2/Controls/MyImage.vb
> +            SetImage(value)
emmm

2024-10-02 18:56 UTC, LTCatt commented on Plain Craft Launcher 2/Modules/Base/MyBitmap.vb
> +                    Dim tempFile = PathTemp & "Cache\MyImage\" & GetHash(FilePathOrResourceName)
我觉得应该直接把网络流拉过来读，而不是先存到本地文件然后再开一个文件流……
在这里开一个网络请求，或者写一个新的底层函数返回一个 Stream？

2024-10-03 05:58 UTC, tangge233 commented on Plain Craft Launcher 2/Modules/Base/MyBitmap.vb
> +                    Dim tempFile = PathTemp & "Cache\MyImage\" & GetHash(FilePathOrResourceName)
用 MemoryStream 接管了 FileStream，看看？

2024-10-03 08:44 UTC, LTCatt approved these changes

2024-10-08 14:16 UTC, LTCatt requested changes
又研究了下，这个实现思路不行，在 UI 线程进行网络请求下载图片是不能接受的……
或许需要在 MyImage 中先把 Source 设置为空，然后后台进行网络请求，在下载结束后再把 Byte() 传给 MyBitmap 进行加载？

2024-10-08 16:17 UTC, tangge233 commented
考虑放上一个“加载中”图片？

2024-10-13 07:53 UTC, LTCatt requested changes

2024-10-13 07:53 UTC, LTCatt commented on Plain Craft Launcher 2/Controls/MyImage.vb
> +                If _UseCache And File.Exists(TempFilePath) And (DateTime.Now - File.GetCreationTime(TempFilePath)) < FileCacheExpiredTime Then NeedDownload = False ' 缓存文件存在且未过期，不需要重下
缓存更新策略还可以优化一下。
如果已有缓存，则无论如何先显示缓存中的图片。如果此时缓存过期，再后台重新下载，下载后更新显示。
这样在更新缓存时玩家也能看到图片 :D

2024-10-13 07:53 UTC, LTCatt commented on Plain Craft Launcher 2/Controls/MyImage.vb
> +                                           End Sub, TaskScheduler.FromCurrentSynchronizationContext())
可以参考 MyLocalModItem 中的 Logo 属性的写法，别用 Task 进行加载

2024-10-13 13:48 UTC, LTCatt requested changes

2024-10-13 13:48 UTC, LTCatt commented on Plain Craft Launcher 2/Pages/PageLaunch/PageLaunchRight.xaml
> +            <local:MyImage UseCache="True" Source="https://objects.lihaoyu.cn/bigcake-blog-images/2024/10/05/6700c8f7cd4b2.jpeg"/>
？

2024-10-13 13:48 UTC, LTCatt commented on Plain Craft Launcher 2/Controls/MyImage.vb
> +                        End Sub)
这个放在 Loader 线程开始前，设置 Source 属性的时候就行吧。

2024-10-13 13:48 UTC, LTCatt commented on Plain Craft Launcher 2/Controls/MyImage.vb
> +    ''' </summary>
需要注册为 DependencyProperty。
默认值为 True。

2024-10-13 13:49 UTC, tangge233 commented on Plain Craft Launcher 2/Pages/PageLaunch/PageLaunchRight.xaml
> +            <local:MyImage UseCache="True" Source="https://objects.lihaoyu.cn/bigcake-blog-images/2024/10/05/6700c8f7cd4b2.jpeg"/>
草，测试忘记删了

2024-10-13 14:46 UTC, tangge233 commented on Plain Craft Launcher 2/Controls/MyImage.vb
> +    ''' </summary>
emmmmm

2024-10-13 19:51 UTC, merged

2024-10-13 19:51 UTC, LTCatt commented on Plain Craft Launcher 2/Controls/MyImage.vb
> +    ''' </summary>
我改完了

2024-10-14 04:28 UTC, tangge233 commented on Plain Craft Launcher 2/Controls/MyImage.vb
> +    ''' </summary>
emmmm 似乎是 WPF 的特性？
新改后的代码测试发现顺序还是会影响实际结果……

使用下面代码很显然是期望不触发缓存机制，但是却使用了缓存
```
<local:MyImage Source="https://objects.lihaoyu.cn/bigcake-blog-images/2024/10/05/6700c8f7cd4b2.jpeg" EnableCache="False"/>
```
将 `EnableCache` 属性移到前面才会正常工作……
```
<local:MyImage EnableCache="False" Source="https://objects.lihaoyu.cn/bigcake-blog-images/2024/10/05/6700c8f7cd4b2.jpeg" />
```

2024-10-14 07:26 UTC, LTCatt commented on Plain Craft Launcher 2/Controls/MyImage.vb
> +    ''' </summary>
修了，等更新的时候再推送 :D