[新功能] LittleSkin OAuth 登录
Hex-Dragon/PCL2 pull request #5021
Opened 2024-10-27 04:15 UTC by wuliaodexiaoluo

Close #4941 （关联投票 #4948  ）

# 此 PR 对微软登录流程进行了破坏性改动
目前微软登录可能无法正常进行

## 登录逻辑

目前实现是如果 ClientID 不为空且 BaseUrl 包含 littleskin.cn 则优先进行 LittleSkin OAuth 登录

如果没有 ClientID 则填写账号密码可以进行原始登录

## 目前比较大的槽点

LittleSkin 登录取消授权不会自动关闭弹窗（技术有限无法修复）
可能用户在启动器输入账号密码后再在网页输入一遍，体验有点不太好，或许可以考虑提示条？
LittleSkin OAuth 登录后可能会有个报错，因为 OAuth 登录不需要保存账号和密码，访问这段数据会抛出索引超界异常

## 注意事项

申请权限需要

User.Read offline_access openid Yggdrasil.PlayerProfiles.Select Yggdrasil.MinecraftToken.Create

这五个权限，其中有 1 个 是可选项但强烈建议申请即 openid，因为 AccessToken 也会编码选择档案的 UUID，可以通过公开 API 查询，但是这段逻辑还没测试过，openid 会编码角色名和 UUID，可以少一步，并且测试可用（没有明显报错）

需要在申请邮件内附上用于正式环境，否则默认申请的是测试环境，测试环境只能应用所有者登录

目前还有点没完成即 LittleSkin OAuth AccessToken 的刷新

写的不好，需要再改改 awa

2024-10-27 04:26 UTC, sulingjiang commented
emmm我是不是不小心删掉了一些配置

2024-10-27 04:29 UTC, sulingjiang requested changes
配置好像变了?
小洛你再看看?

2024-10-27 05:22 UTC, sulingjiang requested changes
相关 Bug 修复

2024-10-27 05:22 UTC, sulingjiang commented on Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
> +        Log("Base64 解码结果" & Encoding.UTF8.GetString(decodedBytes), LogLevel.Normal)
```suggestion
```

2024-10-27 05:22 UTC, sulingjiang commented on Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
> +                Data:=RequestData,
```suggestion
                Data:=RequestData.ToString(0),
```

2024-10-27 05:22 UTC, sulingjiang commented on Plain Craft Launcher 2/Pages/PageLaunch/MyMsgLogin.xaml.vb
> +                    "client_id=" & LittleSkinClientId & "&" &
```suggestion
If(OAuthUrl.ToLower().Contains("littleskin"), LittleSkinClientId, OAuthClientId)
```

2024-10-27 06:36 UTC, wuliaodexiaoluo commented
可能要等到下周去学校做了，下午要回学校上晚自习 awa

2024-10-28 06:42 UTC, wuliaodexiaoluo commented
怎么又是 Unverified 。。。

2024-10-28 07:30 UTC, tangge233 requested changes

2024-10-28 07:30 UTC, tangge233 commented on Plain Craft Launcher 2/Modules/Base/ModNet.vb
> +Imports System.Runtime.Remoting.Messaging
哪里多出来引用……

2024-10-28 07:30 UTC, tangge233 commented on Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
> +Imports System.Net
删去不必要的应用……

2024-10-28 07:30 UTC, tangge233 commented on Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
> +    Public Function Base64Decode(Text As String) As String
比较通用的方法放到 ModBase 里吧……

2024-10-28 09:23 UTC, wuliaodexiaoluo commented on Plain Craft Launcher 2/Modules/Base/ModNet.vb
> +Imports System.Runtime.Remoting.Messaging
可能是写的时候写错方法 Visual Studio 自己加的。。。。
有时候变量或者功能命名有重复按空格就自动补全了

2024-11-02 03:07 UTC, wuliaodexiaoluo commented
Line in 421-428, in ModNet.vb

``` VB.NET
Try
                    If ex.Response Is Nothing Then Exit Try
                    DataStream = ex.Response.GetResponseStream()
                    DataStream.WriteTimeout = Timeout
                    DataStream.ReadTimeout = Timeout
                    Using Reader As New StreamReader(DataStream)
                        Res = Reader.ReadToEnd()
                    End Using

```

由于只返回了内容，无法获取请求头
这会直接影响到 `支持获取请求 ID `
鉴于这部分属于非常底层的实现，改动此部分可能导致大部分功能出现问题，需要加一个重复实现（

2024-11-04 06:44 UTC, wuliaodexiaoluo commented
```
If ex.Message.Contains("authorization_declined") Or ex.Message.Contains("access_denied") Then
                    Finished(New Exception("$你拒绝了 PCL 申请的权限……"))
                    Return
```

明明有检查啊，这又是什么问题？

2024-11-05 04:22 UTC, wuliaodexiaoluo commented
看了一眼，压根看不出来有什么问题，VSCode 也不支持检查，VB 的报错也不大懂。。。
考虑到再继续测下去可能会有被标记的风险，应该是只能等周末上 VisualStudio 看了
如果有人愿意的话也可以帮我看看

2024-11-09 14:10 UTC, wuliaodexiaoluo commented
![image](https://github.com/user-attachments/assets/fc8e9f4a-3dca-44f1-a74b-c8bcd425f4eb)

怎么 504 了（

2024-11-09 14:15 UTC, wuliaodexiaoluo commented
awa，应该是差不多了

2024-11-10 05:44 UTC, wuliaodexiaoluo commented
<details>
<summary>腾讯云干的好事</summary>

![image](https://github.com/user-attachments/assets/e7b51ad0-3f7c-4635-9912-6ed30fdaeb4a)
![image](https://github.com/user-attachments/assets/42f3721f-f680-4795-ac20-73dcab156cb1)

</details>

截止到目前 LittleSkin OAuth 服务仍处于 504 状态无法访问

2024-11-16 01:47 UTC, wuliaodexiaoluo commented
```
If Not LittleSkinToken(0) Then Throw New Exception($"刷新登陆失败，请求 ID 为 {GetJson(LittleSkinToken(3))('X-Yggdralt-Req-ID').ToString}")
```

还有点残留的逻辑没改，等晚上回家再说，然后测试
这周应该能搞定

2024-11-16 01:55 UTC, wuliaodexiaoluo commented
突然发现没更新分支...

2024-11-16 02:35 UTC, wuliaodexiaoluo commented
这个 PR 算是废了，待会重新开一个

2024-11-16 02:35 UTC, closed without merging

2024-11-16 02:41 UTC, wuliaodexiaoluo commented
@LTCatt 抱歉打扰，但是这个 PR 麻烦删一下（（（

2024-11-16 02:58 UTC, JingHai-Lingyun commented
什么情况……？

2024-11-16 03:56 UTC, wuliaodexiaoluo commented
>什么情况……？

操作 BFG 失误...
且涉及到一些敏感内容（（（

2024-11-16 14:05 UTC, LTCatt commented
GitHub 不允许删除 PR，可能得你去找客服……

2024-11-17 08:06 UTC, zkitefly commented
> GitHub 不允许删除 PR，可能得你去找客服……

把 wuliaodexiaoluo:main 删掉，pr 就会自动消失

2024-11-17 12:41 UTC, wuliaodexiaoluo commented
>不行的。PR 一旦被创建可能只能通过删库才能删掉。当然被封号也可以起到类似的作用

我正在尝试通过隐私信息删除工单来删除 PR，不过显然 GitHub 对免费计划账户的支持工单并不重视

2024-11-17 12:50 UTC, wuliaodexiaoluo commented
>GitHub 不允许删除 PR，可能得你去找客服……

显然，如果我现在去找客服提交删除请求，可能整个存储库都得被扬了，因为这玩意根本删不掉（（（
参考 [GitHub 私人信息删除政策](https://docs.github.com/zh/site-policy/content-removal-policies/github-private-information-removal-policy)

2024-11-17 13:21 UTC, LTCatt commented
![image](https://github.com/user-attachments/assets/b54f92bf-1566-4c89-a539-91f7c70c4e39)