当 PCL 在桌面运行时给予提示
Hex-Dragon/PCL2 pull request #5176
Opened 2024-11-24 14:20 UTC by Hill23333

如图：
![image](https://github.com/user-attachments/assets/38eb00c7-749d-4a38-b939-6982f66499f5)
![image](https://github.com/user-attachments/assets/7d2ff37c-0dc8-4770-9787-28fb8ef6c958)
测试了Win11 Win10 Win7都可以触发

我觉得提示词要改改，但是我想不到更好的...

Close #5163

2024-11-24 17:58 UTC, LTCatt approved these changes

2024-11-25 01:40 UTC, shimoranla requested changes

2024-11-25 01:40 UTC, shimoranla commented on Plain Craft Launcher 2/Application.xaml.vb
> +                MyMsgBox("不建议将 PCL 存储到桌面中运行！" & vbCrLf & "将 PCL 存储在桌面运行可能造成游戏无法启动。", "环境警告", "我知道了", IsWarn:=True)
```suggestion
                MyMsgBox("不建议在桌面文件夹中运行 PCL！" & vbCrLf & "PCL 目前在桌面文件夹中运行，可能导致游戏无法正常启动。", "环境警告", "我知道了", IsWarn:=True)
```

2024-11-25 01:40 UTC, shimoranla commented on Plain Craft Launcher 2/Application.xaml.vb
> +                MyMsgBox("不建议将 PCL 存储到桌面中运行！" & vbCrLf & "将 PCL 存储在桌面运行可能造成游戏无法启动。", "环境警告", "我知道了", IsWarn:=True)
或许还有更好的

2024-11-25 05:49 UTC, Hill23333 commented on Plain Craft Launcher 2/Application.xaml.vb
> +                MyMsgBox("不建议将 PCL 存储到桌面中运行！" & vbCrLf & "将 PCL 存储在桌面运行可能造成游戏无法启动。", "环境警告", "我知道了", IsWarn:=True)
我觉得对于小白来说去除「文件夹」三个字更好理解。其他的来说这个提示确实更好。

2024-11-25 15:33 UTC, Hill23333 commented on Plain Craft Launcher 2/Application.xaml.vb
> +                MyMsgBox("不建议在桌面中运行 PCL！" & vbCrLf & "PCL 目前在桌面中运行，可能导致游戏无法正常启动。", "环境警告", "我知道了", IsWarn:=True)
ok

2024-12-05 15:12 UTC, LTCatt commented
https://github.com/Hex-Dragon/PCL2/issues/5163#issuecomment-2520586504

2024-12-05 15:12 UTC, closed without merging